DELETE FROM t_perm_permitem WHERE FID = '2A5WA/Z4YAET';
INSERT INTO t_perm_permitem(FID,FPREPERMITEMID,FBIZAPPID,FINHERITMODE,FGROUP,FNUMBER) VALUES ('2A5WA/Z4YAET','47150e89000000ac',' ','10','10','HRQXX0170'); 
DELETE FROM t_perm_permitem WHERE FID = '2DA5R551WK78';
INSERT INTO t_perm_permitem(FID,FPREPERMITEMID,FBIZAPPID,FINHERITMODE,FGROUP,FNUMBER) VALUES ('2DA5R551WK78','47150e89000000ac',' ','10','10','HRQXX0230'); 
DELETE FROM t_perm_permitem WHERE FID = '2JJA911D4=+P';
INSERT INTO t_perm_permitem(FID,FPREPERMITEMID,FBIZAPPID,FINHERITMODE,FGROUP,FNUMBER) VALUES ('2JJA911D4=+P','47150e89000000ac',' ','10','10','HRQXX0355'); 
DELETE FROM t_perm_permitem WHERE FID = '2JJA9WIIEEA=';
INSERT INTO t_perm_permitem(FID,FPREPERMITEMID,FBIZAPPID,FINHERITMODE,FGROUP,FNUMBER) VALUES ('2JJA9WIIEEA=','47150e89000000ac',' ','10','10','HRQXX0360'); 
DELETE FROM t_perm_permitem WHERE FID = '2JJA7W54XO32';
INSERT INTO t_perm_permitem(FID,FPREPERMITEMID,FBIZAPPID,FINHERITMODE,FGROUP,FNUMBER) VALUES ('2JJA7W54XO32','47150e89000000ac',' ','10','10','HRQXX0350'); 
DELETE FROM t_perm_permitem WHERE FID = '2BEGMIB+UGLX';
INSERT INTO t_perm_permitem(FID,FPREPERMITEMID,FBIZAPPID,FINHERITMODE,FGROUP,FNUMBER) VALUES ('2BEGMIB+UGLX','47150e89000000ac',' ','10','10','HRQXX0204'); 
DELETE FROM t_perm_permitem WHERE FID = '2BEGNF7Y+24F';
INSERT INTO t_perm_permitem(FID,FPREPERMITEMID,FBIZAPPID,FINHERITMODE,FGROUP,FNUMBER) VALUES ('2BEGNF7Y+24F','47150e89000000ac',' ','10','10','HRQXX0205'); 
DELETE FROM t_perm_permitem WHERE FID = '2BEGPA0K7+N/';
INSERT INTO t_perm_permitem(FID,FPREPERMITEMID,FBIZAPPID,FINHERITMODE,FGROUP,FNUMBER) VALUES ('2BEGPA0K7+N/','47150e89000000ac',' ','10','10','HRQXX0207'); 
DELETE FROM t_perm_permitem WHERE FID = '2BEGOC9WTO6A';
INSERT INTO t_perm_permitem(FID,FPREPERMITEMID,FBIZAPPID,FINHERITMODE,FGROUP,FNUMBER) VALUES ('2BEGOC9WTO6A','47150e89000000ac',' ','10','10','HRQXX0206'); 
DELETE FROM t_perm_permitem WHERE FID = '2BEGLE+8G4I9';
INSERT INTO t_perm_permitem(FID,FPREPERMITEMID,FBIZAPPID,FINHERITMODE,FGROUP,FNUMBER) VALUES ('2BEGLE+8G4I9','47150e89000000ac',' ','10','10','HRQXX0203'); 
DELETE FROM t_perm_permitem WHERE FID = '2BEGQLHRN9JX';
INSERT INTO t_perm_permitem(FID,FPREPERMITEMID,FBIZAPPID,FINHERITMODE,FGROUP,FNUMBER) VALUES ('2BEGQLHRN9JX','47150e89000000ac',' ','10','10','HRQXX0208'); 
DELETE FROM t_perm_permitem WHERE FID = '2OPEM0HF65UC';
INSERT INTO t_perm_permitem(FID,FPREPERMITEMID,FBIZAPPID,FINHERITMODE,FGROUP,FNUMBER) VALUES ('2OPEM0HF65UC','47150e89000000ac',' ','10','10','HRQXX0585'); 


DELETE FROM t_perm_permitem_l WHERE FPKID = '2OPEMEYMYLI8';
INSERT INTO t_perm_permitem_l(FID,FPKID,FLOCALEID,FDESCRIPTION,FNAME) VALUES ('2OPEM0HF65UC','2OPEMEYMYLI8','zh_CN','版本修订','版本修订'); 
DELETE FROM t_perm_permitem_l WHERE FPKID = '2JJAC0NSIP6+';
INSERT INTO t_perm_permitem_l(FID,FPKID,FLOCALEID,FDESCRIPTION,FNAME) VALUES ('2JJA911D4=+P','2JJAC0NSIP6+','zh_CN','劳动合同_改签','劳动合同_改签'); 
DELETE FROM t_perm_permitem_l WHERE FPKID = '2JJAC0NSIOHR';
INSERT INTO t_perm_permitem_l(FID,FPKID,FLOCALEID,FDESCRIPTION,FNAME) VALUES ('2JJA9WIIEEA=','2JJAC0NSIOHR','zh_CN','用工协议_新签   ','用工协议_新签   '); 
DELETE FROM t_perm_permitem_l WHERE FPKID = '2JJAC0NSIP6/';
INSERT INTO t_perm_permitem_l(FID,FPKID,FLOCALEID,FDESCRIPTION,FNAME) VALUES ('2JJA7W54XO32','2JJAC0NSIP6/','zh_CN','劳动合同_新签','劳动合同_新签'); 
DELETE FROM t_perm_permitem_l WHERE FPKID = '2A5WA8PQZR5X';
INSERT INTO t_perm_permitem_l(FID,FPKID,FLOCALEID,FDESCRIPTION,FNAME) VALUES ('2A5WA/Z4YAET','2A5WA8PQZR5X','zh_CN','历史版本信息','历史版本信息'); 
DELETE FROM t_perm_permitem_l WHERE FPKID = '2DA5RMS3JUHV';
INSERT INTO t_perm_permitem_l(FID,FPKID,FLOCALEID,FDESCRIPTION,FNAME) VALUES ('2DA5R551WK78','2DA5RMS3JUHV','zh_CN','查看全部日志','查看全部日志'); 
DELETE FROM t_perm_permitem_l WHERE FPKID = '2BEGRC9UI87/';
INSERT INTO t_perm_permitem_l(FID,FPKID,FLOCALEID,FDESCRIPTION,FNAME) VALUES ('2BEGMIB+UGLX','2BEGRC9UI87/','zh_CN','终止签署','终止签署'); 
DELETE FROM t_perm_permitem_l WHERE FPKID = '2BEGRC9UG7F/';
INSERT INTO t_perm_permitem_l(FID,FPKID,FLOCALEID,FDESCRIPTION,FNAME) VALUES ('2BEGNF7Y+24F','2BEGRC9UG7F/','zh_CN','确认归档','确认归档'); 
DELETE FROM t_perm_permitem_l WHERE FPKID = '2BEGRC9UI870';
INSERT INTO t_perm_permitem_l(FID,FPKID,FLOCALEID,FDESCRIPTION,FNAME) VALUES ('2BEGPA0K7+N/','2BEGRC9UI870','zh_CN','完成签署','完成签署'); 
DELETE FROM t_perm_permitem_l WHERE FPKID = '2BEGRC9UG7F0';
INSERT INTO t_perm_permitem_l(FID,FPKID,FLOCALEID,FDESCRIPTION,FNAME) VALUES ('2BEGOC9WTO6A','2BEGRC9UG7F0','zh_CN','发起签署','发起签署'); 
DELETE FROM t_perm_permitem_l WHERE FPKID = '2BEGRC9UI871';
INSERT INTO t_perm_permitem_l(FID,FPKID,FLOCALEID,FDESCRIPTION,FNAME) VALUES ('2BEGLE+8G4I9','2BEGRC9UI871','zh_CN','终止流程','终止流程'); 
DELETE FROM t_perm_permitem_l WHERE FPKID = '2BEGRC9UG7F1';
INSERT INTO t_perm_permitem_l(FID,FPKID,FLOCALEID,FDESCRIPTION,FNAME) VALUES ('2BEGQLHRN9JX','2BEGRC9UG7F1','zh_CN','企业签署','企业签署'); 




