<?xml version="1.0" encoding="UTF-8"?>

<DeployAppMetadata>
  <Multilanguage>false</Multilanguage>
  <MasterId>XYRL3+A8Z+Z</MasterId>
  <Id>4HRF=77Y8588</Id>
  <DesignMetas>
    <DesignAppMeta>
      <DevType>2</DevType>
      <AppVersion>1.5.0</AppVersion>
      <Modifier>2027699484829418496</Modifier>
      <DataXml>
        <AppMetadata>
          <DevType>2</DevType>
          <Isv>tdkw</Isv>
          <Number>tdkw_hbss_ext</Number>
          <Id>4HRF=77Y8588</Id>
          <ParentId>XYRL3+A8Z+Z</ParentId>
          <MasterId>XYRL3+A8Z+Z</MasterId>
          <AppElement>
            <AppElement>
              <Number>tdkw_hbss_ext</Number>
              <Id>4HRF=77Y8588</Id>
              <Version>1.5.0</Version>
              <UserType>,1,</UserType>
            </AppElement>
          </AppElement>
          <InheritPath>XYRL3+A8Z+Z</InheritPath>
        </AppMetadata>
      </DataXml>
      <Description></Description>
      <DbRoute>hmp</DbRoute>
      <Isv>tdkw</Isv>
      <OpenType>0</OpenType>
      <AllUserApp>0</AllUserApp>
      <Number>tdkw_hbss_ext</Number>
      <IndustryId>0</IndustryId>
      <Id>4HRF=77Y8588</Id>
      <Seq>60</Seq>
      <CreateDate>1730442809868</CreateDate>
      <MainFormType>0</MainFormType>
      <BizCloudID>0PEIU203SX4Y</BizCloudID>
      <DependencyID></DependencyID>
      <Image>/icons/pc/entrance/hr_zwtxfa_48_48.png</Image>
      <OrgFunc></OrgFunc>
      <Visible>1</Visible>
      <Dependency></Dependency>
      <HelpURL></HelpURL>
      <Label></Label>
      <ModelType>AppModel</ModelType>
      <MainFormName>HR基础服务应用首页-栅格</MainFormName>
      <ParentId>XYRL3+A8Z+Z</ParentId>
      <BackImage></BackImage>
      <HomeURL></HomeURL>
      <MasterId>XYRL3+A8Z+Z</MasterId>
      <Creater>2027699484829418496</Creater>
      <MainFormID>/L8LX1/XHON=</MainFormID>
      <SimpleNumber>hbss</SimpleNumber>
      <InheritPath>XYRL3+A8Z+Z</InheritPath>
      <RefAppId></RefAppId>
      <UserType>,1,</UserType>
      <DeployStatus>2</DeployStatus>
    </DesignAppMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployAppMetadata>
