<?xml version="1.0" encoding="UTF-8"?>

<DeployMetadata>
  <Id>2020287583640209408</Id>
  <DesignMetas>
    <DesignConvertRuleMeta>
      <DevType>0</DevType>
      <ModifyDate>1724924338395</ModifyDate>
      <DataXml>
        <ConvertRuleMetadata>
          <DevType>0</DevType>
          <Isv>tdkw</Isv>
          <RuleElement>
            <ConvertRuleElement>
              <FieldMapPolicy>
                <FieldMapPolicy>
                  <FieldMaps>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>billno</TargetFieldKey>
                      <SourceFieldKey/>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>auditor</TargetFieldKey>
                      <SourceFieldKey/>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>auditdate</TargetFieldKey>
                      <SourceFieldKey/>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>Formula</ConvertType>
                      <TargetFieldKey>tdkw_calc_org</TargetFieldKey>
                      <ConvertType2>Formula,tdkw_adminorg</ConvertType2>
                      <Formula>
                        <CRFormula>
                          <Expression>tdkw_adminorg</Expression>
                          <Description/>
                          <ExprTran>所属组织</ExprTran>
                        </CRFormula>
                      </Formula>
                      <SumType>Join</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>tdkw_assess_year</TargetFieldKey>
                      <ConvertType2>SourceField,tdkw_assess_year</ConvertType2>
                      <SourceFieldKey>tdkw_assess_year</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>modifierfield</TargetFieldKey>
                      <SourceFieldKey/>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>modifydatefield</TargetFieldKey>
                      <SourceFieldKey/>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>tdkw_adminorg</TargetFieldKey>
                      <ConvertType2>SourceField,tdkw_adminorg</ConvertType2>
                      <SourceFieldKey>tdkw_adminorg</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>tdkw_weight</TargetFieldKey>
                      <ConvertType2>SourceField,tdkw_weight</ConvertType2>
                      <SourceFieldKey>tdkw_weight</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>tdkw_unit</TargetFieldKey>
                      <ConvertType2>SourceField,tdkw_unit</ConvertType2>
                      <SourceFieldKey>tdkw_unit</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>tdkw_ctr_annual_val</TargetFieldKey>
                      <ConvertType2>SourceField,tdkw_ctr_annual_val</ConvertType2>
                      <SourceFieldKey>tdkw_ctr_annual_val</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>tdkw_calc_result</TargetFieldKey>
                      <SourceFieldKey/>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>tdkw_target_value</TargetFieldKey>
                      <ConvertType2>SourceField,tdkw_target_value</ConvertType2>
                      <SourceFieldKey>tdkw_target_value</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>tdkw_cmp_annual_val</TargetFieldKey>
                      <ConvertType2>SourceField,tdkw_annual_val</ConvertType2>
                      <SourceFieldKey>tdkw_annual_val</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>tdkw_eval_res</TargetFieldKey>
                      <ConvertType2>SourceField,tdkw_eval_res</ConvertType2>
                      <SourceFieldKey>tdkw_eval_res</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>tdkw_metric</TargetFieldKey>
                      <ConvertType2>SourceField,tdkw_metric</ConvertType2>
                      <SourceFieldKey>tdkw_metric</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>tdkw_superorg</TargetFieldKey>
                      <ConvertType2>SourceField,tdkw_superorg</ConvertType2>
                      <SourceFieldKey>tdkw_superorg</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>Formula</ConvertType>
                      <TargetFieldKey>tdkw_org_perf_subentryid</TargetFieldKey>
                      <ConvertType2>Formula,tdkw_subentryentity.id</ConvertType2>
                      <Formula>
                        <CRFormula>
                          <Expression>tdkw_subentryentity.id</Expression>
                          <Description/>
                          <ExprTran>指标.内码</ExprTran>
                        </CRFormula>
                      </Formula>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>tdkw_metric_str</TargetFieldKey>
                      <ConvertType2>SourceField,tdkw_metric_str</ConvertType2>
                      <SourceFieldKey>tdkw_metric_str</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>tdkw_metric_desc</TargetFieldKey>
                      <ConvertType2>SourceField,tdkw_metric_desc</ConvertType2>
                      <SourceFieldKey>tdkw_metric_desc</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>tdkw_rating_standard</TargetFieldKey>
                      <ConvertType2>SourceField,tdkw_rating_standard</ConvertType2>
                      <SourceFieldKey>tdkw_rating_standard</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>tdkw_metric_type</TargetFieldKey>
                      <ConvertType2>SourceField,tdkw_area_type</ConvertType2>
                      <SourceFieldKey>tdkw_area_type</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>tdkw_modifierfield</TargetFieldKey>
                      <SourceFieldKey/>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>tdkw_modifydatefield</TargetFieldKey>
                      <SourceFieldKey/>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>tdkw_adminorg1</TargetFieldKey>
                      <ConvertType2>SourceField,tdkw_adminorg</ConvertType2>
                      <SourceFieldKey>tdkw_adminorg</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>tdkw_eval_res1</TargetFieldKey>
                      <ConvertType2>SourceField,tdkw_eval_res_list</ConvertType2>
                      <SourceFieldKey>tdkw_eval_res_list</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>Formula</ConvertType>
                      <TargetFieldKey>tdkw_perf_metricsid</TargetFieldKey>
                      <ConvertType2>Formula,id</ConvertType2>
                      <Formula>
                        <CRFormula>
                          <Expression>id</Expression>
                          <Description/>
                          <ExprTran>组织绩效指标.内码</ExprTran>
                        </CRFormula>
                      </Formula>
                      <SumType>First</SumType>
                    </FieldMapItem>
                  </FieldMaps>
                </FieldMapPolicy>
              </FieldMapPolicy>
              <FilterPolicy>
                <FilterPolicy>
                  <Condition>
                    <CRCondition>
                      <FilterString>{"filterRow":[],"forList":false}</FilterString>
                      <Description/>
                      <ExprTran/>
                    </CRCondition>
                  </Condition>
                </FilterPolicy>
              </FilterPolicy>
              <LinkEntityPolicy>
                <LinkEntityPolicy>
                  <SourceSubEntryKey/>
                  <TargetEntryKey>tdkw_calc_metric_detail</TargetEntryKey>
                  <TargetSubEntryKey/>
                  <SourceEntryKey>tdkw_subentryentity</SourceEntryKey>
                  <LinkType>Link</LinkType>
                  <SourceLayout>tdkw_org_perf_metrics</SourceLayout>
                </LinkEntityPolicy>
              </LinkEntityPolicy>
              <utoSave>true</utoSave>
              <SysStatus>0</SysStatus>
              <AttachmentPanelMapPolicy>
                <AttachmentPanelMapPolicy>
                  <Items>
                    <AttachmentPanelMapItem>
                      <TargetAttachmentPanel>attachmentpanel</TargetAttachmentPanel>
                      <Id>4C1NS1CGW=0E</Id>
                      <Seq>1</Seq>
                    </AttachmentPanelMapItem>
                  </Items>
                </AttachmentPanelMapPolicy>
              </AttachmentPanelMapPolicy>
              <OptionPolicy>
                <OptionPolicy>
                  <MergeIntoLinkRow>true</MergeIntoLinkRow>
                  <PushOneTime>true</PushOneTime>
                  <OnlyReadBillTable>false</OnlyReadBillTable>
                </OptionPolicy>
              </OptionPolicy>
              <TargetEntityNumber>tdkw_calculate_score</TargetEntityNumber>
              <SourceEntityNumber>tdkw_org_perf_metrics</SourceEntityNumber>
              <Id>2020287583640209408</Id>
              <GroupByPolicy>
                <GroupByPolicy>
                  <GroupByField/>
                  <GroupMode3>OneToOne</GroupMode3>
                  <GroupMode2>OneToOne</GroupMode2>
                  <GroupByField2/>
                  <GroupByField3/>
                  <GroupMode>AllInOne</GroupMode>
                </GroupByPolicy>
              </GroupByPolicy>
              <Name>下推计算分数</Name>
            </ConvertRuleElement>
          </RuleElement>
          <Id>2020287583640209408</Id>
          <CreateDate>1724037047000</CreateDate>
          <ParentId/>
          <MasterId/>
          <BizappId>4A6IGSR0AFR3</BizappId>
          <InheritPath/>
        </ConvertRuleMetadata>
      </DataXml>
      <ModifierId>2005735093842332672</ModifierId>
      <ModelType>ConvertRuleModel</ModelType>
      <Isv>tdkw</Isv>
      <Version>1724924338443</Version>
      <Enabled>true</Enabled>
      <ParentId></ParentId>
      <MasterId></MasterId>
      <SysStatus>0</SysStatus>
      <BizappId>4A6IGSR0AFR3</BizappId>
      <TargetEntityNumber>tdkw_calculate_score</TargetEntityNumber>
      <SourceEntityNumber>tdkw_org_perf_metrics</SourceEntityNumber>
      <Id>2020287583640209408</Id>
      <InheritPath></InheritPath>
      <CreateDate>1724037047000</CreateDate>
    </DesignConvertRuleMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployMetadata>
