<?xml version="1.0" encoding="UTF-8"?>

<DeployAppMetadata>
  <Multilanguage>false</Multilanguage>
  <MasterId>4A6IGSR0AFR3</MasterId>
  <Id>4A6IGSR0AFR3</Id>
  <DesignMetas>
    <DesignAppMeta>
      <DevType>0</DevType>
      <AppVersion>1.5.0</AppVersion>
      <Modifier>2005809205306574848</Modifier>
      <DataXml>
        <AppMetadata>
          <DevType>0</DevType>
          <AppFunctionPackets>
            <AppFunctionPacketElement>
              <Number>MainPage</Number>
              <Name>首页</Name>
              <Description/>
              <Id>4A6IGSWLWC=W</Id>
              <Leaf>0</Leaf>
              <ParentId/>
              <Seq>1</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>BasicSettings</Number>
              <Name>基础设置</Name>
              <Description/>
              <Id>4A6IUEPW=Y26</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>2</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>OrgPerformance</Number>
              <Name>组织绩效单据</Name>
              <Description/>
              <Id>4ANTK6C4QH37</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>3</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>hmt</Number>
              <Name>历史模型事务</Name>
              <Description/>
              <Id>4APHG8PYCD91</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>6</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>Map</Number>
              <Name>组织绩效地图</Name>
              <Description/>
              <Id>4AWB6WIQ9DU5</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>4</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>Audit</Number>
              <Name>组织绩效审核</Name>
              <Description/>
              <Id>4AWB9BCWFRZM</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>5</Seq>
            </AppFunctionPacketElement>
          </AppFunctionPackets>
          <AppMenus>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>bd97dfe5bd</Number>
              <FormName>亮灯规则</FormName>
              <FormNumber>tdkw_light_rule</FormNumber>
              <Parameter/>
              <Id>2019025346657110016</Id>
              <Seq>1</Seq>
              <FormId>4CDO/DRATVX6</FormId>
              <ParameterType>ListShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj3_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>2019024594719066112</ParentId>
              <VectorImage>kdfont kdfont-tongyongtubiao5</VectorImage>
              <Name>亮灯规则</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>caa8a4a30c</Number>
              <FormName>组织绩效多页签展示页</FormName>
              <FormNumber>tdkw_org_perf_list_show</FormNumber>
              <Parameter/>
              <Id>2020984195936957440</Id>
              <Seq>1</Seq>
              <FormId>4B5PG/OIG7FK</FormId>
              <ParameterType>FormShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>4A6IGSR0AFR3</ParentId>
              <VectorImage>kdfont kdfont-tongyongtubiao3</VectorImage>
              <Name>组织绩效列表</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>5f1659c765</Number>
              <FormName>计算规则</FormName>
              <FormNumber>tdkw_calculation_rules</FormNumber>
              <Parameter/>
              <Id>2019031372991154176</Id>
              <Seq>2</Seq>
              <FormId>4AWNOH=QS=VI</FormId>
              <ParameterType>ListShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj4_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>2019024594719066112</ParentId>
              <VectorImage>kdfont kdfont-cebianlantubiao1beifen</VectorImage>
              <Name>计算规则</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>3c53f6bbbe</Number>
              <FormName>指标库</FormName>
              <FormNumber>tdkw_perf_metrics</FormNumber>
              <Parameter/>
              <Id>2020981488631165952</Id>
              <Seq>2</Seq>
              <FormId>4=XC2R/KUWBO</FormId>
              <ParameterType>ListShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>4A6IGSR0AFR3</ParentId>
              <VectorImage>kdfont kdfont-tongyongtubiao3</VectorImage>
              <Name>组织绩效指标库</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>2d5098e92e</Number>
              <FormName>通知人员配置表</FormName>
              <FormNumber>tdkw_notify_config</FormNumber>
              <Parameter/>
              <Id>2019031864051878912</Id>
              <Seq>3</Seq>
              <FormId>4AINJOMJECHD</FormId>
              <ParameterType>BaseShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj3_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>2019024594719066112</ParentId>
              <VectorImage>kdfont kdfont-tongyongtubiao5</VectorImage>
              <Name>通知人员配置表</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>27cd5f2b29</Number>
              <FormName>组织绩效指标审批单</FormName>
              <FormNumber>tdkw_metrics_audit</FormNumber>
              <Parameter/>
              <Id>2022582815597647872</Id>
              <Seq>3</Seq>
              <FormId>4BBIH7TG1OSD</FormId>
              <ParameterType>ListShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj2_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>4A6IGSR0AFR3</ParentId>
              <VectorImage>kdfont kdfont-tongyongtubiao4</VectorImage>
              <Name>组织绩效审核列表</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>14e833d931</Number>
              <Parameter/>
              <LinkUrl/>
              <Id>2019024594719066112</Id>
              <Seq>4</Seq>
              <IconShortcut>/icons/pc/application/tysj_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>4A6IGSR0AFR3</ParentId>
              <VectorImage>kdfont kdfont-tongyongtubiao3</VectorImage>
              <Name>基础设置</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>0edca4a513</Number>
              <FormName>指标类型</FormName>
              <FormNumber>tdkw_metric_type</FormNumber>
              <Parameter/>
              <Id>2020982879017775104</Id>
              <Seq>4</Seq>
              <FormId>4=XG6A4++B=N</FormId>
              <ParameterType>ListShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj2_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>2019024594719066112</ParentId>
              <VectorImage>kdfont kdfont-tongyongtubiao4</VectorImage>
              <Name>指标类型</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>85a621ec0e</Number>
              <FormName>组织绩效地图表单</FormName>
              <FormNumber>tdkw_performance_map_form</FormNumber>
              <Parameter/>
              <Id>2028434506616165376</Id>
              <Seq>5</Seq>
              <FormId>4C0T4+CYX0R/</FormId>
              <ParameterType>FormShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj5_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>4A6IGSR0AFR3</ParentId>
              <VectorImage>kdfont kdfont-cebianlantubiao6beifen</VectorImage>
              <Name>组织绩效地图</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Caption>帮助中心</Caption>
              <Description>帮助中心</Description>
              <FormName>应用入门中心</FormName>
              <FormNumber>bas_appstarted</FormNumber>
              <Parameter>{"caption":{"zh_CN":"帮助中心"}}</Parameter>
              <Id>4B+Z+P1SQ69#hpce</Id>
              <Seq>32766</Seq>
              <FormId>/WXHVRP15OWF</FormId>
              <IconShortcut>/icons/pc/entrance/helpcentre.png</IconShortcut>
              <Visible>0</Visible>
              <ParentId>4A6IGSR0AFR3</ParentId>
              <VectorImage>kdfont kdfont-tishixinxi_l</VectorImage>
              <Name>帮助中心</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
          </AppMenus>
          <Isv>tdkw</Isv>
          <Number>tdkw_opa</Number>
          <Id>4A6IGSR0AFR3</Id>
          <BizCloudID>24BBHV84L8E9</BizCloudID>
          <ParentId/>
          <MasterId/>
          <AppElement>
            <AppElement>
              <MainFormNumber>tdkw_opa_apphome</MainFormNumber>
              <Description>面向组织进行的绩效考核与评价</Description>
              <DbRoute>opmc</DbRoute>
              <OpenType>0</OpenType>
              <AllUserApp>0</AllUserApp>
              <Number>tdkw_opa</Number>
              <Id>4A6IGSR0AFR3</Id>
              <Seq>10</Seq>
              <MainFormType>0</MainFormType>
              <DependencyID/>
              <Image>/icons/pc/entrance/hr_zzgl_48_48.png</Image>
              <OrgFunc/>
              <Visible>1</Visible>
              <Dependency/>
              <HelpURL/>
              <Label/>
              <MainFormName>组织绩效考核_应用首页</MainFormName>
              <Version>1.5.0</Version>
              <BackImage/>
              <HomeURL/>
              <MainFormID>4A6IGVWYYBE1</MainFormID>
              <Name>组织绩效考核</Name>
              <SimpleNumber/>
              <UserType>,1,</UserType>
              <DeployStatus>2</DeployStatus>
            </AppElement>
          </AppElement>
          <InheritPath/>
        </AppMetadata>
      </DataXml>
      <Description></Description>
      <DbRoute>opmc</DbRoute>
      <Isv>tdkw</Isv>
      <OpenType>0</OpenType>
      <AllUserApp>0</AllUserApp>
      <Number>tdkw_opa</Number>
      <IndustryId>0</IndustryId>
      <Id>4A6IGSR0AFR3</Id>
      <Seq>10</Seq>
      <CreateDate>1723104551739</CreateDate>
      <MainFormType>0</MainFormType>
      <BizCloudID>24BBHV84L8E9</BizCloudID>
      <DependencyID></DependencyID>
      <Image>/icons/pc/entrance/hr_zzgl_48_48.png</Image>
      <OrgFunc></OrgFunc>
      <Visible>1</Visible>
      <ModifyDate>1725260757269</ModifyDate>
      <Dependency></Dependency>
      <HelpURL></HelpURL>
      <Label></Label>
      <ModelType>AppModel</ModelType>
      <MainFormName>组织绩效考核_应用首页</MainFormName>
      <ParentId></ParentId>
      <BackImage></BackImage>
      <HomeURL></HomeURL>
      <MasterId></MasterId>
      <Creater>1935588399943648256</Creater>
      <MainFormID>4A6IGVWYYBE1</MainFormID>
      <SimpleNumber></SimpleNumber>
      <InheritPath></InheritPath>
      <RefAppId></RefAppId>
      <UserType>,1,</UserType>
      <DeployStatus>2</DeployStatus>
    </DesignAppMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployAppMetadata>
