<?xml version="1.0" encoding="UTF-8"?>

<DeployAppMetadata>
  <Multilanguage>false</Multilanguage>
  <MasterId>3C438QESNO1T</MasterId>
  <Id>3C438QESNO1T</Id>
  <DesignMetas>
    <DesignAppMeta>
      <DevType>0</DevType>
      <AppVersion>5.0.001.0</AppVersion>
      <Modifier>1760310820044270594</Modifier>
      <DataXml>
        <AppMetadata>
          <DevType>0</DevType>
          <AppFunctionPackets>
            <AppFunctionPacketElement>
              <Number>MainPage</Number>
              <Name>首页</Name>
              <Description/>
              <Id>3C438QGQTD3K</Id>
              <Leaf>0</Leaf>
              <ParentId/>
              <Seq>1</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>subordinate</Number>
              <Name>人员下级</Name>
              <Description/>
              <Id>3D/U6NU=BG/X</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>5</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>ZFY</Number>
              <Name>祝福语</Name>
              <Description/>
              <Id>3DCTO/PFDD0F</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>6</Seq>
            </AppFunctionPacketElement>
          </AppFunctionPackets>
          <AppMenus>
            <AppMenuElement>
              <Caption>帮助中心</Caption>
              <Description>帮助中心</Description>
              <FormName>应用入门中心</FormName>
              <FormNumber>bas_appstarted</FormNumber>
              <Parameter>{"caption":{"zh_CN":"帮助中心"}}</Parameter>
              <Id>3C7J52D+APW#hpce</Id>
              <Seq>32766</Seq>
              <FormId>/WXHVRP15OWF</FormId>
              <IconShortcut>/icons/pc/entrance/helpcentre.png</IconShortcut>
              <Visible>0</Visible>
              <ParentId>3C438QESNO1T</ParentId>
              <VectorImage>kdfont kdfont-tishixinxi_l</VectorImage>
              <Name>帮助中心</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
          </AppMenus>
          <Isv>tdkw</Isv>
          <Number>tdkw_appauthority</Number>
          <Id>3C438QESNO1T</Id>
          <BizCloudID>18Y2T5WS5AFV</BizCloudID>
          <ParentId/>
          <MasterId/>
          <AppElement>
            <AppElement>
              <MainFormNumber>tdkw_appauthority_apphome</MainFormNumber>
              <Description>这是一个新的应用</Description>
              <DbRoute>secd</DbRoute>
              <OpenType>0</OpenType>
              <AllUserApp>0</AllUserApp>
              <Number>tdkw_appauthority</Number>
              <Id>3C438QESNO1T</Id>
              <Seq>264</Seq>
              <MainFormType>0</MainFormType>
              <DependencyID/>
              <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
              <OrgFunc/>
              <Visible>0</Visible>
              <Dependency/>
              <HelpURL/>
              <Label/>
              <MainFormName>移动端权限_应用首页</MainFormName>
              <Version>5.0.001.0</Version>
              <BackImage/>
              <HomeURL/>
              <MainFormID>3C438R6MLYXE</MainFormID>
              <Name>应用权限</Name>
              <SimpleNumber/>
              <UserType>,1,</UserType>
              <DeployStatus>2</DeployStatus>
            </AppElement>
          </AppElement>
          <InheritPath/>
        </AppMetadata>
      </DataXml>
      <Description></Description>
      <DbRoute>secd</DbRoute>
      <Isv>tdkw</Isv>
      <OpenType>0</OpenType>
      <AllUserApp>0</AllUserApp>
      <Number>tdkw_appauthority</Number>
      <IndustryId>0</IndustryId>
      <Id>3C438QESNO1T</Id>
      <Seq>264</Seq>
      <CreateDate>1687139185654</CreateDate>
      <MainFormType>0</MainFormType>
      <BizCloudID>18Y2T5WS5AFV</BizCloudID>
      <DependencyID></DependencyID>
      <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
      <OrgFunc></OrgFunc>
      <Visible>0</Visible>
      <ModifyDate>1698378953862</ModifyDate>
      <Dependency></Dependency>
      <HelpURL></HelpURL>
      <Label></Label>
      <ModelType>AppModel</ModelType>
      <MainFormName>移动端权限_应用首页</MainFormName>
      <ParentId></ParentId>
      <BackImage></BackImage>
      <HomeURL></HomeURL>
      <MasterId></MasterId>
      <Creater>1631049357887288320</Creater>
      <MainFormID>3C438R6MLYXE</MainFormID>
      <SimpleNumber></SimpleNumber>
      <InheritPath></InheritPath>
      <RefAppId></RefAppId>
      <UserType>,1,</UserType>
      <DeployStatus>2</DeployStatus>
    </DesignAppMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployAppMetadata>
