<?xml version="1.0" encoding="UTF-8"?>

<DeployAppMetadata>
  <Multilanguage>false</Multilanguage>
  <MasterId>217WYC/L9U7E</MasterId>
  <Id>4E/7AN1DAFA1</Id>
  <DesignMetas>
    <DesignAppMeta>
      <DevType>2</DevType>
      <AppVersion>1.5.0</AppVersion>
      <Modifier>1425399182121766912</Modifier>
      <DataXml>
        <AppMetadata>
          <DevType>2</DevType>
          <AppFunctionPackets>
            <AppFunctionPacketElement>
              <Number>establishment</Number>
              <Name>编制管理</Name>
              <Description>纯二开模块</Description>
              <Id>4HKZ/X71T/VS</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>115</Seq>
            </AppFunctionPacketElement>
          </AppFunctionPackets>
          <AppMenus>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>486fbb192c</Number>
              <FormName>编制计划催办配置</FormName>
              <FormNumber>dgdl_planperson</FormNumber>
              <Parameter/>
              <Id>2073278739050921984</Id>
              <Seq>1</Seq>
              <FormId>3VU3=PA+CSB8</FormId>
              <ParameterType>ListShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj5_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>2073278502072759296</ParentId>
              <VectorImage>kdfont kdfont-cebianlantubiao6beifen</VectorImage>
              <Name>编制计划催办配置</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>681e9179e1</Number>
              <FormName>年度编制计划</FormName>
              <FormNumber>dgdl_planyear_pc</FormNumber>
              <Parameter/>
              <Id>2073279362198680576</Id>
              <Seq>2</Seq>
              <FormId>460L8TCTJ79M</FormId>
              <ParameterType>ListShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj5_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>2073278502072759296</ParentId>
              <VectorImage>kdfont kdfont-cebianlantubiao6beifen</VectorImage>
              <Name>年度编制计划</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>cb7f8a4966</Number>
              <FormName>月度编制计划</FormName>
              <FormNumber>dgdl_planmonth</FormNumber>
              <Parameter/>
              <Id>2073279708346187776</Id>
              <Seq>3</Seq>
              <FormId>3J9I/WMVJSQZ</FormId>
              <ParameterType>ListShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj3_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>2073278502072759296</ParentId>
              <VectorImage>kdfont kdfont-tongyongtubiao5</VectorImage>
              <Name>月度编制计划</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>68e6541cf9</Number>
              <FormName>编制变更申请</FormName>
              <FormNumber>tdkw_bzchange_request</FormNumber>
              <Parameter/>
              <Id>2087179917870511104</Id>
              <Seq>5</Seq>
              <FormId>4=/YH9S+2R5G</FormId>
              <ParameterType>ListShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj5_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>1452025116635600896</ParentId>
              <VectorImage>kdfont kdfont-cebianlantubiao6beifen</VectorImage>
              <Name>编制变更申请</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>1bbf69cdd3</Number>
              <FormName/>
              <Parameter/>
              <Id>2073278502072759296</Id>
              <Seq>10</Seq>
              <FormId/>
              <IconShortcut>/icons/pc/application/tysj5_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>4E/7AN1DAFA1</ParentId>
              <VectorImage>kdfont kdfont-cebianlantubiao6beifen</VectorImage>
              <Name>编制管理</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
          </AppMenus>
          <Isv>tdkw</Isv>
          <Number>tdkw_homs_ext</Number>
          <Id>4E/7AN1DAFA1</Id>
          <ParentId>217WYC/L9U7E</ParentId>
          <MasterId>217WYC/L9U7E</MasterId>
          <AppElement>
            <AppElement>
              <Number>tdkw_homs_ext</Number>
              <Id>4E/7AN1DAFA1</Id>
              <Version>1.5.0</Version>
              <UserType>,1,</UserType>
            </AppElement>
          </AppElement>
          <InheritPath>217WYC/L9U7E</InheritPath>
        </AppMetadata>
      </DataXml>
      <Description></Description>
      <DbRoute>hr</DbRoute>
      <Isv>tdkw</Isv>
      <OpenType>0</OpenType>
      <AllUserApp>0</AllUserApp>
      <Number>tdkw_homs_ext</Number>
      <IndustryId>0</IndustryId>
      <Id>4E/7AN1DAFA1</Id>
      <Seq>121</Seq>
      <CreateDate>1726804266651</CreateDate>
      <MainFormType>0</MainFormType>
      <BizCloudID>0MUWQ6HSY5JA</BizCloudID>
      <DependencyID></DependencyID>
      <Image>/icons/pc/entrance/hr_zzgl_48_48.png</Image>
      <OrgFunc>21</OrgFunc>
      <Visible>1</Visible>
      <ModifyDate>1733377189901</ModifyDate>
      <Dependency></Dependency>
      <HelpURL></HelpURL>
      <Label></Label>
      <ModelType>AppModel</ModelType>
      <MainFormName>组织管理_应用首页</MainFormName>
      <ParentId>217WYC/L9U7E</ParentId>
      <BackImage></BackImage>
      <HomeURL></HomeURL>
      <MasterId>217WYC/L9U7E</MasterId>
      <Creater>2027699484829418496</Creater>
      <MainFormID>217WYDGZJ/R2</MainFormID>
      <SimpleNumber></SimpleNumber>
      <InheritPath>217WYC/L9U7E</InheritPath>
      <RefAppId></RefAppId>
      <UserType>,1,</UserType>
      <DeployStatus>2</DeployStatus>
    </DesignAppMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployAppMetadata>
