<?xml version="1.0" encoding="UTF-8"?>

<DeployAppMetadata>
  <Multilanguage>false</Multilanguage>
  <MasterId>2W6FZY1I61I+</MasterId>
  <Id>3==6P77F4X8W</Id>
  <DesignMetas>
    <DesignAppMeta>
      <DevType>2</DevType>
      <AppVersion>1.5.0</AppVersion>
      <Modifier>1425399182121766912</Modifier>
      <DataXml>
        <AppMetadata>
          <DevType>2</DevType>
          <AppFunctionPackets>
            <AppFunctionPacketElement>
              <Number>mygateway</Number>
              <Name>我的门户-卡片</Name>
              <Description/>
              <Id>3=D3DC=KSU/E</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>7</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>echarts</Number>
              <Name>图表</Name>
              <Description/>
              <Id>3C554Y1G=7FX</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>8</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>tdkw_report</Number>
              <Name>报表</Name>
              <Description/>
              <Id>3EC4PPF=NI8F</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>10</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>tdkw_page</Number>
              <Name>页面</Name>
              <Description/>
              <Id>3KVPEVNKCTB9</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>11</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>xyji_monitor</Number>
              <Name>运营监控</Name>
              <Description/>
              <Id>3NCMH673B519</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>12</Seq>
            </AppFunctionPacketElement>
          </AppFunctionPackets>
          <AppMenus>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>ff1d62d698</Number>
              <FormName>门户视图方案</FormName>
              <FormNumber>hrobs_portalscheme</FormNumber>
              <Parameter/>
              <Id>1733950601852732416</Id>
              <Seq>1</Seq>
              <FormId>2WTRYQE+EA1W</FormId>
              <ParameterType>ListShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj4_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>1733949806965015552</ParentId>
              <VectorImage>kdfont kdfont-cebianlantubiao1beifen</VectorImage>
              <Name>门户视图方案</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>44b1381cdc</Number>
              <FormName/>
              <Parameter/>
              <Id>1733949806965015552</Id>
              <Seq>3</Seq>
              <FormId/>
              <IconShortcut>/icons/pc/application/tysj4_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>3==6P77F4X8W</ParentId>
              <VectorImage>kdfont kdfont-cebianlantubiao1beifen</VectorImage>
              <Name>门户视图方案</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>f540ee95b8</Number>
              <FormName>门户Banner图片</FormName>
              <FormNumber>tdkw_portalbanner</FormNumber>
              <Parameter/>
              <Id>1733950224818357248</Id>
              <Seq>4</Seq>
              <FormId>3==Y53C=3819</FormId>
              <ParameterType>ListShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj4_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>3==6P77F4X8W</ParentId>
              <VectorImage>kdfont kdfont-cebianlantubiao1beifen</VectorImage>
              <Name>图片Banner</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
          </AppMenus>
          <Isv>tdkw</Isv>
          <Number>tdkw_hrobs_ext</Number>
          <Id>3==6P77F4X8W</Id>
          <ParentId>2W6FZY1I61I+</ParentId>
          <MasterId>2W6FZY1I61I+</MasterId>
          <AppElement>
            <AppElement>
              <Number>tdkw_hrobs_ext</Number>
              <Id>3==6P77F4X8W</Id>
            </AppElement>
          </AppElement>
          <InheritPath>2W6FZY1I61I+</InheritPath>
        </AppMetadata>
      </DataXml>
      <Description></Description>
      <DbRoute>hmp</DbRoute>
      <Isv>tdkw</Isv>
      <OpenType>0</OpenType>
      <AllUserApp>0</AllUserApp>
      <Number>tdkw_hrobs_ext</Number>
      <IndustryId>0</IndustryId>
      <Id>3==6P77F4X8W</Id>
      <Seq>105</Seq>
      <CreateDate>1684379443737</CreateDate>
      <MainFormType>0</MainFormType>
      <BizCloudID>0PEIU203SX4Y</BizCloudID>
      <DependencyID></DependencyID>
      <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
      <OrgFunc></OrgFunc>
      <Visible>1</Visible>
      <ModifyDate>1732706173473</ModifyDate>
      <Dependency></Dependency>
      <HelpURL></HelpURL>
      <Label></Label>
      <ModelType>AppModel</ModelType>
      <MainFormName>HR运营基础服务_应用首页</MainFormName>
      <ParentId>2W6FZY1I61I+</ParentId>
      <BackImage></BackImage>
      <HomeURL></HomeURL>
      <MasterId>2W6FZY1I61I+</MasterId>
      <Creater>1687593626118461440</Creater>
      <MainFormID>2W6FZZRX5IQD</MainFormID>
      <SimpleNumber></SimpleNumber>
      <InheritPath>2W6FZY1I61I+</InheritPath>
      <RefAppId></RefAppId>
      <UserType>,1,</UserType>
      <DeployStatus>2</DeployStatus>
    </DesignAppMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployAppMetadata>
