 DELETE from t_cr_coderule where fid = '4A6P2NRA//ZR';
 INSERT INTO t_cr_coderule(FID, FNUMBER, FBIZOBJECTID, FSPLITSIGN, FCTRLMODE, FAPPMODE, FEXAMPLE, FEXAMPLELENGTH, FENABLE, FSTATUS, FCREATORID, FCREATETIME, FMODIFIERID, FMODIFYTIME, FMASTERID, FISUPDATERECOVER, FISNONBREAK, FISCHECKCODE, FISAPPCONDITION, FISAPPORG, FISLOG, FISSERIALNUMBER, FISUNIQUE, FISMODIFIABLE, FISADDVIEW, FFILTERCONDITION, FCONDITIONDESC, FISFAST) VALUES ( '4A6P2NRA//ZR','4A6P154P=8PU','tdkw_perf_metrics',' ','1','2',' ',' ','1','C', 0,{ts'2024-08-08 17:19:30'},1935588399943648256,{ts'2024-08-08 17:19:30'},'4A6P2NRA//ZR','0','0','0','0','1','0','1','0','0','1',' ',' ','1');
DELETE from t_cr_coderule_l where fid = '4A6P2NRA//ZR';
INSERT INTO t_cr_coderule_l(FPKID, FID, FLOCALEID, FNAME) VALUES ('4A6P2NRA//=H','4A6P2NRA//ZR','zh_CN','指标库');
DELETE from t_cr_coderuleentry where fid = '4A6P2NRA//ZR';
INSERT t_cr_coderuleentry(FENTRYID, FID, FSEQ, FATTRIBUTETYPE, FATTUSINGMODE, FVALUEATRIBUTE, FFORMAT, FSETTINGVALUE, FLENGTH, FINITIAL, FSTEP, FADDCHAR, FISSPLITSIGN, FADDSTYLE, FCUTSTYLE, FISSORTITEM, FSPLITSIGN, FISVISABLE) VALUES ('4A6P2NVS0Z7C','4A6P2NRA//ZR',0,'1','1',' ','XY',' ',8,1,1,' ','0','1','1','0',' ','1');
INSERT t_cr_coderuleentry(FENTRYID, FID, FSEQ, FATTRIBUTETYPE, FATTUSINGMODE, FVALUEATRIBUTE, FFORMAT, FSETTINGVALUE, FLENGTH, FINITIAL, FSTEP, FADDCHAR, FISSPLITSIGN, FADDSTYLE, FCUTSTYLE, FISSORTITEM, FSPLITSIGN, FISVISABLE) VALUES ('4A6P2NVS0Z7D','4A6P2NRA//ZR',1,'16',' ',' ',' ',' ',4,1,1,' ','0','1','1','0',' ','1');


