 DELETE from t_cr_coderule where fid = '4BF=L4U3DAGF';
 INSERT INTO t_cr_coderule(FID, FNUMBER, FBIZOBJECTID, FSPLITSIGN, FCTRLMODE, FAPPMODE, FEXAMPLE, FEXAMPLELENGTH, FENABLE, FSTATUS, FCREATORID, FCREATETIME, FMODIFIERID, FMODIFYTIME, FMASTERID, FISUPDATERECOVER, FISNONBREAK, FISCHECKCODE, FISAPPCONDITION, FISAPPORG, FISLOG, FISSERIALNUMBER, FISUNIQUE, FISMODIFIABLE, FISADDVIEW, FFILTERCONDITION, FCONDITIONDESC, FISFAST) VALUES ( '4BF=L4U3DAGF','4BF=HDRB8F8X','tdkw_target_alignment','-','1','2',' ',' ','1','C', 0,{ts'2024-08-22 17:15:16'},1774867234695580672,{ts'2024-08-22 17:15:16'},'4BF=L4U3DAGF','0','0','0','0','1','0','1','0','0','1',' ',' ','1');
DELETE from t_cr_coderule_l where fid = '4BF=L4U3DAGF';
INSERT INTO t_cr_coderule_l(FPKID, FID, FLOCALEID, FNAME) VALUES ('4BF=L4U7/Q+P','4BF=L4U3DAGF','zh_CN','指标对齐');
DELETE from t_cr_coderuleentry where fid = '4BF=L4U3DAGF';
INSERT t_cr_coderuleentry(FENTRYID, FID, FSEQ, FATTRIBUTETYPE, FATTUSINGMODE, FVALUEATRIBUTE, FFORMAT, FSETTINGVALUE, FLENGTH, FINITIAL, FSTEP, FADDCHAR, FISSPLITSIGN, FADDSTYLE, FCUTSTYLE, FISSORTITEM, FSPLITSIGN, FISVISABLE) VALUES ('4BF=L4XY1BCG','4BF=L4U3DAGF',0,'1','1',' ','zbfj',' ',8,1,1,' ','0','1','1','0',' ','1');
INSERT t_cr_coderuleentry(FENTRYID, FID, FSEQ, FATTRIBUTETYPE, FATTUSINGMODE, FVALUEATRIBUTE, FFORMAT, FSETTINGVALUE, FLENGTH, FINITIAL, FSTEP, FADDCHAR, FISSPLITSIGN, FADDSTYLE, FCUTSTYLE, FISSORTITEM, FSPLITSIGN, FISVISABLE) VALUES ('4BF=L4XY1BCH','4BF=L4U3DAGF',1,'9',' ',' ','yyyyMMdd',' ',8,1,1,' ','1','1','1','0','-','1');
INSERT t_cr_coderuleentry(FENTRYID, FID, FSEQ, FATTRIBUTETYPE, FATTUSINGMODE, FVALUEATRIBUTE, FFORMAT, FSETTINGVALUE, FLENGTH, FINITIAL, FSTEP, FADDCHAR, FISSPLITSIGN, FADDSTYLE, FCUTSTYLE, FISSORTITEM, FSPLITSIGN, FISVISABLE) VALUES ('4BF=L4XY1BCI','4BF=L4U3DAGF',2,'16',' ',' ',' ',' ',8,1,1,' ','1','1','1','0','-','1');


