 DELETE from t_cr_coderule where fid = '4A6M=/WYY444';
 INSERT INTO t_cr_coderule(FID, FNUMBER, FBIZOBJECTID, FSPLITSIGN, FCTRLMODE, FAPPMODE, FEXAMPLE, FEXAMPLELENGTH, FENABLE, FSTATUS, FCREATORID, FCREATETIME, FMODIFIERID, FMODIFYTIME, FMASTERID, FISUPDATERECOVER, FISNONBREAK, FISCHECKCODE, FISAPPCONDITION, FISAPPORG, FISLOG, FISSERIALNUMBER, FISUNIQUE, FISMODIFIABLE, FISADDVIEW, FFILTERCONDITION, FCONDITIONDESC, FISFAST) VALUES ( '4A6M=/WYY444','4A6M9+YONEW/','tdkw_usage_category',' ','1','2',' ',' ','1','C', 0,{ts'2024-08-08 16:49:36'},1935588399943648256,{ts'2024-08-08 17:12:18'},'4A6M=/WYY444','0','0','0','0','1','0','1','0','0','1',' ',' ','1');
DELETE from t_cr_coderule_l where fid = '4A6M=/WYY444';
INSERT INTO t_cr_coderule_l(FPKID, FID, FLOCALEID, FNAME) VALUES ('4A6M=/X0JIND','4A6M=/WYY444','zh_CN','指标用途分类');
DELETE from t_cr_coderuleentry where fid = '4A6M=/WYY444';
INSERT t_cr_coderuleentry(FENTRYID, FID, FSEQ, FATTRIBUTETYPE, FATTUSINGMODE, FVALUEATRIBUTE, FFORMAT, FSETTINGVALUE, FLENGTH, FINITIAL, FSTEP, FADDCHAR, FISSPLITSIGN, FADDSTYLE, FCUTSTYLE, FISSORTITEM, FSPLITSIGN, FISVISABLE) VALUES ('4A6MOWYPOLUQ','4A6M=/WYY444',0,'1','1',' ','XY',' ',8,1,1,' ','0','1','1','0',' ','1');
INSERT t_cr_coderuleentry(FENTRYID, FID, FSEQ, FATTRIBUTETYPE, FATTUSINGMODE, FVALUEATRIBUTE, FFORMAT, FSETTINGVALUE, FLENGTH, FINITIAL, FSTEP, FADDCHAR, FISSPLITSIGN, FADDSTYLE, FCUTSTYLE, FISSORTITEM, FSPLITSIGN, FISVISABLE) VALUES ('4A6MOWYPOLUR','4A6M=/WYY444',1,'16',' ',' ',' ',' ',3,1,1,' ','0','1','1','0',' ','1');


