DELETE FROM t_sch_taskdefine WHERE FID = '3G8J1/K5P+QU';
INSERT INTO t_sch_taskdefine(FID,FCLASSNAME,FAPPID,FNUMBER) VALUES ('3G8J1/K5P+QU','tdkw.esc.tdkw_myteam.business.AuthorityInitTaskPlugin','tdkw_employee_service','AuthorityInitTaskPlugin');

DELETE FROM t_sch_taskdefine_l WHERE FPKID = '3G8J1/K5P+1K';
INSERT INTO t_sch_taskdefine_l(FID,FPKID,FLOCALEID,FNAME) VALUES ('3G8J1/K5P+QU','3G8J1/K5P+1K','zh_CN','递归获取指定职层的下属');
DELETE FROM t_sch_taskdefine_l WHERE FPKID = '3G8J1/K5P+1L';
INSERT INTO t_sch_taskdefine_l(FID,FPKID,FLOCALEID,FNAME) VALUES ('3G8J1/K5P+QU','3G8J1/K5P+1L','zh_TW','遞歸獲取指定職層的下屬');

DELETE FROM T_SCH_JOB WHERE FID = '3D1+/+J6I46B';
INSERT INTO T_SCH_JOB(FID,FTASKCLASSNAME,FTASKDEFINEID,FRUNBYUSERID,FJOBTYPE,FTIMEOUT,FRUNBYLANG,FSTATUS,FPARAMS,FRUNBYORGID,FNUMBER,FCONCURRENT) VALUES ('3D1+/+J6I46B','tdkw.esc.tdkw_myteam.business.AuthorityInitTaskPlugin','3G8J1/K5P+QU',1681098732466095104,'BIZ',0,' ','1','{}',0,'tdkw_employee_service_bos_AuthorityInitTaskPlugin','0');

DELETE FROM T_SCH_JOB_l WHERE FPKID = '3D1+/+J6I3I2';
INSERT INTO T_SCH_JOB_l(FID,FPKID,FLOCALEID,FNAME) VALUES ('3D1+/+J6I46B','3D1+/+J6I3I2','zh_CN','递归获取指定职层的下属调度任务');
DELETE FROM T_SCH_JOB_l WHERE FPKID = '3D1+/+J6I3I3';
INSERT INTO T_SCH_JOB_l(FID,FPKID,FLOCALEID,FNAME) VALUES ('3D1+/+J6I46B','3D1+/+J6I3I3','zh_TW','遞歸獲取指定職層的下屬調度任務');

DELETE FROM T_SCH_SCHEDULE WHERE FID = '3D1+1SBKJNF7';
INSERT INTO T_SCH_SCHEDULE(FTWENTY,FFIVE,FELEVEN,FNINE,FNO,FSUN,FTWO,FEIGHT,FNOV,FPLAN,FWED,FHOST,FTWENTYTWO,FFOUR,FMAR,FSEP,FENDTIME,FSIX,FREPEATMODE,FMAY,FTHIRTYONE,FBYDAYORWEEK,FTWENTYSEVEN,FTWENTYSIX,FTHIRTEEN,FAUG,FDESC,FFIFTEEN,FTWENTYONE,FBYWEEK,FTUES,FSEVENTEEN,FSEVEN,FTWENTYFOUR,FMON,FTHIRTY,FTHREE,FFOURTEEN,FJAN,FNINETEEN,FTHUR,FTEN,FFRI,FJOBID,FSTARTTIME,FOCT,FAPR,FSIXTEEN,FID,FSAT,FONE,FTWENTYEIGHT,FTWENTYTHREE,FTWELVE,FNOWEEK,FSTATUS,FNUMBER,FTWENTYFIVE,FEIGHTEEN,FCYCLENUM,FTWENTYNINE,FJUL,FDEC,FJUN,FFEB) VALUES ('0','0','0','0',' ','0','0','0','0','0 37 17 29 6 ? 2023','0','172.18.11.152','0','0','0','0',{ts'2024-06-22  00:00:00'},'0','n','0','0','d','0','0','0','0','事件不重复','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','3D1+/+J6I46B',{ts'2023-06-29  00:00:00'},'0','0','0','3D1+1SBKJNF7','0','0','0','0','0',' ','1','bos_AuthorityInitTaskPlugin','0','0',1,'0','0','0','0','0');

DELETE FROM T_SCH_SCHEDULE_l WHERE FPKID = '3D1+1SBKJO3G';
INSERT INTO T_SCH_SCHEDULE_l(FID,FPKID,FLOCALEID,FNAME) VALUES ('3D1+1SBKJNF7','3D1+1SBKJO3G','zh_CN','递归获取指定职层的下属调度计划');
DELETE FROM T_SCH_SCHEDULE_l WHERE FPKID = '3D1+1SBKJO3H';
INSERT INTO T_SCH_SCHEDULE_l(FID,FPKID,FLOCALEID,FNAME) VALUES ('3D1+1SBKJNF7','3D1+1SBKJO3H','zh_TW','遞歸獲取指定職層的下屬調度計劃');

