<?xml version="1.0" encoding="UTF-8"?>

<DeployAppMetadata>
  <Multilanguage>false</Multilanguage>
  <MasterId>4CHFD+7332QW</MasterId>
  <Id>4CHFD+7332QW</Id>
  <DesignMetas>
    <DesignAppMeta>
      <DevType>0</DevType>
      <AppVersion>1.5.0</AppVersion>
      <Modifier>2027699484829418496</Modifier>
      <DataXml>
        <AppMetadata>
          <DevType>0</DevType>
          <AppFunctionPackets>
            <AppFunctionPacketElement>
              <Number>MainPage</Number>
              <Name>首页</Name>
              <Description/>
              <Id>4CHFD+9B41C6</Id>
              <Leaf>0</Leaf>
              <ParentId/>
              <Seq>1</Seq>
            </AppFunctionPacketElement>
          </AppFunctionPackets>
          <Isv>tdkw</Isv>
          <Number>tdkw_activitydemo</Number>
          <Id>4CHFD+7332QW</Id>
          <BizCloudID>11FWSEDXBS99</BizCloudID>
          <ParentId/>
          <MasterId/>
          <AppElement>
            <AppElement>
              <MainFormNumber>tdkw_activitydemo_apphome</MainFormNumber>
              <Description>活动案例</Description>
              <DbRoute>hrb</DbRoute>
              <OpenType>0</OpenType>
              <AllUserApp>0</AllUserApp>
              <Number>tdkw_activitydemo</Number>
              <Id>4CHFD+7332QW</Id>
              <Seq>105</Seq>
              <MainFormType>0</MainFormType>
              <DependencyID/>
              <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
              <OrgFunc/>
              <Visible>1</Visible>
              <Dependency/>
              <HelpURL/>
              <Label/>
              <MainFormName>活动案例_应用首页</MainFormName>
              <Version>1.5.0</Version>
              <BackImage/>
              <HomeURL/>
              <MainFormID>4CHFD+WP4U5=</MainFormID>
              <Name>活动案例</Name>
              <SimpleNumber/>
              <UserType>,1,</UserType>
              <DeployStatus>2</DeployStatus>
            </AppElement>
          </AppElement>
          <InheritPath/>
        </AppMetadata>
      </DataXml>
      <Description></Description>
      <DbRoute>hrb</DbRoute>
      <Isv>tdkw</Isv>
      <OpenType>0</OpenType>
      <AllUserApp>0</AllUserApp>
      <Number>tdkw_activitydemo</Number>
      <IndustryId>0</IndustryId>
      <Id>4CHFD+7332QW</Id>
      <Seq>105</Seq>
      <CreateDate>1725341987726</CreateDate>
      <MainFormType>0</MainFormType>
      <BizCloudID>11FWSEDXBS99</BizCloudID>
      <DependencyID></DependencyID>
      <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
      <OrgFunc></OrgFunc>
      <Visible>1</Visible>
      <ModifyDate>1725801596341</ModifyDate>
      <Dependency></Dependency>
      <HelpURL></HelpURL>
      <Label></Label>
      <ModelType>AppModel</ModelType>
      <MainFormName>活动案例_应用首页</MainFormName>
      <ParentId></ParentId>
      <BackImage></BackImage>
      <HomeURL></HomeURL>
      <MasterId></MasterId>
      <Creater>2027699484829418496</Creater>
      <MainFormID>4CHFD+WP4U5=</MainFormID>
      <SimpleNumber></SimpleNumber>
      <InheritPath></InheritPath>
      <RefAppId></RefAppId>
      <UserType>,1,</UserType>
      <DeployStatus>2</DeployStatus>
    </DesignAppMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployAppMetadata>
