/**
 * This is a kingdee cosmic template project that is automatically generated by the Kingdee cosmic development assistant plugin. 
 * If there are any issues during the use process, you can provide feedback to the kingdee developer community website.
 * Website: https://developer.kingdee.com/developer?productLineId=29
 * Author: liebin.zheng
 * Generate Date: 2024-06-17 11:45:38
 */
package cds0.opmc.cea.common;

/**
 * opmc云cea应用-通用常量类<br>
 * 代码中不能存在硬编码敏感信息，如账号、密码、http外链、ftp外链、邮箱等。<br>
 * 标识或缓存的常量，需以"KEY_"、"FID_"、"ENTRY_"或"SUBENTRY_"作为变量的前缀。<br>
 *
 * @author cds0
 * @date 2024-06-17 11:45:38
 */
public class AppflgConstant {
	
	public static final String KEY_APP_NAME = "opmc-cea";
	public static final String ID = "id";
	public static final String ENTRYID = "entryid";
	public static final String CEA_DIMSETTING = "cea_dimsetting";
	public static final String CEA_EVALDIMSETTING = "cea_evaldimsetting";
	public static final String CEA_ASSESSOBJ = "cea_assessobj";
	public static final String CEA_ASSESSACTIVITY = "cea_assessactivity";
	public static final String CEA_ASSESSACTCONFIRM ="ces_assessactconfirm";
	public static final String CEA_ACTFINISHCONFIRM ="cea_actfinishconfirm";
	public static final String CEA_ASSOBJSCOITEMINS = "cea_assobjscoitemins";
	public static final String CEA_PROCESSMANAGE = "cea_processmanage";
	public static final String CEA_ASSOBJ_TOSTARTUP = "cea_assobj_tostartup";
	public static final String CEA_ASSOBJ_ASSESSING = "cea_assobj_assessing";
	public static final String CEA_ASSOBJ_FINISHED = "cea_assobj_finished";
	public static final String CEA_DIMSETTINGSELECT = "cea_dimsettingselect";
	public static final String CEA_ASSESSERMONIT = "cea_assessermonit";
	public static final String CEA_DIMASSESSERSETLIST = "cea_dimassessersetlist";
	public static final String CEA_ASSESSPREVIEW = "cea_assesspreview";
	public static final String OP_KEY_CONFIRM = "confirm";
	public static final String OP_KEY_SAVE = "save";
	public static final String OP_KEY_STARTUP = "startup";
	public static final String OP_KEY_DELETE = "delact";
	public static final String OP_KEY_FINISH = "finish";
	public static final String OP_KEY_PROCESSMANAGE = "processmanage";
	public static final String OP_KEY_CANCEL = "cancel";
	public static final String OP_KEY_ASSESSOBJADD = "assessObjAdd";
	public static final String OP_KEY_ASSESSOBJSTARTUP = "startup";
	public static final String OP_KEY_DELETEASSOBJ = "deleteassobj";
	public static final String ENTRYENTITY = "entryentity";
	public static final String GROUPDIMNAME = "groupdimname";
	public static final String DESCRIPTION = "description";
	public static final String DIMWEIGHTDIGEST= "dimweightdigest";
	public static final String NAME = "name";
	public static final String NUMBER = "number";
	public static final String PERSON = "person";
	public static final String DIMENSION = "dimension";
	public static final String DIMINDEX = "dimindex";
	public static final String DIMNAME = "dimname";
	public static final String DIMWEIGHT = "dimweight";
	public static final String EVALROLE = "evalrole";
	public static final String ASSESS_TASK = "cea_assesstask";
	public static final String ASSESS_TASK_STATUS = "assestaskstatus";
	public static final String ASSESS_ACTIVITY_STATUS = "activitystatus";
	public static final String MSG_TEMPLATE = "msg_template";
	public static final String ASSESS_TASK_LIST = "cea_assesstask_list";
	public static final String PERF_FIlE = "pmd_perffile";
	public static final String ASSESS_ACTIVITY_ID = "activityId";
	public static final String DIMASSWSSER = "cea_dimassesser";
	public static final String ASSESS_FORM = "cea_assessformfix";
	public static final String ASSESS_FORM_ROW = "cea_assessformrowfix";
	public static final String ASSESSOBJ = "cea_assessobj";
	public static final String CEA_DIMASSESSER = "cea_dimassesser";
	public static final String ASSESSER = "assesser";
	public static final String EVALDIM = "evaldim";
	public static final String DIMASSESSERSETLIST = "cea_dimassessersetlist";
	public static final String PERFLEVEL = "hbss_perflevel";
	public static final String ACTIVITY_ID = "activity_id";

	public static final String GRADEDETAILS = "cea_gradedetails";
	public static final String KEY_ASSESSERUPDATE = "modifyassesser";
	public static final String KEY_BUTTON = "buttonkey";
	public static final String KEY_ASSESSEROBJIDS = "assesserobjids";
	public static final String SCORE_SYSTEM = "hbss_scoresystem";
	public static final String CEA_EVALUATION_PREVIEW = "cea_evaluation_preview";
	public static final String CEA_ASSERSEEKCONF = "cea_asserseekconf";
}
