<?xml version="1.0" encoding="UTF-8"?>

<DeployAppMetadata>
  <Multilanguage>false</Multilanguage>
  <MasterId>W11R1282DJK</MasterId>
  <Id>4FQ3K/XTFP3M</Id>
  <DesignMetas>
    <DesignAppMeta>
      <DevType>2</DevType>
      <AppVersion>10.9.999.0</AppVersion>
      <Modifier>2027699484829418496</Modifier>
      <DataXml>
        <AppMetadata>
          <DevType>2</DevType>
          <Isv>tdkw</Isv>
          <Number>tdkw_haos_ext</Number>
          <Id>4FQ3K/XTFP3M</Id>
          <ParentId>W11R1282DJK</ParentId>
          <MasterId>W11R1282DJK</MasterId>
          <AppElement>
            <AppElement>
              <Number>tdkw_haos_ext</Number>
              <Id>4FQ3K/XTFP3M</Id>
            </AppElement>
          </AppElement>
          <InheritPath>W11R1282DJK</InheritPath>
        </AppMetadata>
      </DataXml>
      <Description></Description>
      <DbRoute>hr</DbRoute>
      <Isv>tdkw</Isv>
      <OpenType>0</OpenType>
      <AllUserApp>0</AllUserApp>
      <Number>tdkw_haos_ext</Number>
      <IndustryId>0</IndustryId>
      <Id>4FQ3K/XTFP3M</Id>
      <Seq>10</Seq>
      <CreateDate>1728468986193</CreateDate>
      <MainFormType>0</MainFormType>
      <BizCloudID>0PEIU203SX4Y</BizCloudID>
      <DependencyID></DependencyID>
      <Image>/icons/pc/application/xingzhenzuzhi_48_48.png</Image>
      <OrgFunc></OrgFunc>
      <Visible>0</Visible>
      <Dependency></Dependency>
      <HelpURL></HelpURL>
      <Label></Label>
      <ModelType>AppModel</ModelType>
      <MainFormName>行政组织首页</MainFormName>
      <ParentId>W11R1282DJK</ParentId>
      <BackImage></BackImage>
      <HomeURL></HomeURL>
      <MasterId>W11R1282DJK</MasterId>
      <Creater>2027699484829418496</Creater>
      <MainFormID>/L57NHJZGX2L</MainFormID>
      <SimpleNumber>haos</SimpleNumber>
      <InheritPath>W11R1282DJK</InheritPath>
      <RefAppId></RefAppId>
      <UserType>1</UserType>
      <DeployStatus>2</DeployStatus>
    </DesignAppMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployAppMetadata>
