DELETE FROM t_perm_permitem WHERE FID = '20SIHU+A8+HL';
INSERT INTO t_perm_permitem(FID,FPREPERMITEMID,FBIZAPPID,FINHERITMODE,FDESCRIPTION,FGROUP,FNUMBER) VALUES ('20SIHU+A8+HL','47150e89000000ac',' ','10',' ','10','HRQXX0039'); 
DELETE FROM t_perm_permitem WHERE FID = '20SIJS1PMCOS';
INSERT INTO t_perm_permitem(FID,FPREPERMITEMID,FBIZAPPID,FINHERITMODE,FDESCRIPTION,FGROUP,FNUMBER) VALUES ('20SIJS1PMCOS','47150e89000000ac',' ','10',' ','10','HRQXX0040'); 


DELETE FROM t_perm_permitem_l WHERE FPKID = '20SIMXW0RSTM';
INSERT INTO t_perm_permitem_l(FID,FPKID,FLOCALEID,FNAME) VALUES ('20SIHU+A8+HL','20SIMXW0RSTM','zh_CN','开具离职证明'); 
DELETE FROM t_perm_permitem_l WHERE FPKID = '20SIMXW0PYS7';
INSERT INTO t_perm_permitem_l(FID,FPKID,FLOCALEID,FNAME) VALUES ('20SIJS1PMCOS','20SIMXW0PYS7','zh_CN','确认开具完成'); 




