<?xml version="1.0" encoding="UTF-8"?>

<DeployAppMetadata>
  <Multilanguage>false</Multilanguage>
  <MasterId>14SL2L0H+OZM</MasterId>
  <Id>4HRDSB6XQ5R7</Id>
  <DesignMetas>
    <DesignAppMeta>
      <DevType>2</DevType>
      <AppVersion>1.5.0</AppVersion>
      <Modifier>2027699484829418496</Modifier>
      <DataXml>
        <AppMetadata>
          <DevType>2</DevType>
          <Isv>tdkw</Isv>
          <Number>tdkw_hbjm_ext</Number>
          <Id>4HRDSB6XQ5R7</Id>
          <ParentId>14SL2L0H+OZM</ParentId>
          <MasterId>14SL2L0H+OZM</MasterId>
          <AppElement>
            <AppElement>
              <Number>tdkw_hbjm_ext</Number>
              <Id>4HRDSB6XQ5R7</Id>
              <Version>1.5.0</Version>
              <UserType>,1,</UserType>
            </AppElement>
          </AppElement>
          <InheritPath>14SL2L0H+OZM</InheritPath>
        </AppMetadata>
      </DataXml>
      <Description></Description>
      <DbRoute>hr</DbRoute>
      <Isv>tdkw</Isv>
      <OpenType>0</OpenType>
      <AllUserApp>0</AllUserApp>
      <Number>tdkw_hbjm_ext</Number>
      <IndustryId>0</IndustryId>
      <Id>4HRDSB6XQ5R7</Id>
      <Seq>93</Seq>
      <CreateDate>1730441846893</CreateDate>
      <MainFormType>0</MainFormType>
      <BizCloudID>0PEIU203SX4Y</BizCloudID>
      <DependencyID></DependencyID>
      <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
      <OrgFunc></OrgFunc>
      <Visible>0</Visible>
      <Dependency></Dependency>
      <HelpURL></HelpURL>
      <Label></Label>
      <ModelType>AppModel</ModelType>
      <MainFormName>HR基础职位_应用首页</MainFormName>
      <ParentId>14SL2L0H+OZM</ParentId>
      <BackImage></BackImage>
      <HomeURL></HomeURL>
      <MasterId>14SL2L0H+OZM</MasterId>
      <Creater>2027699484829418496</Creater>
      <MainFormID>14SL2NGHT/UQ</MainFormID>
      <SimpleNumber></SimpleNumber>
      <InheritPath>14SL2L0H+OZM</InheritPath>
      <RefAppId></RefAppId>
      <UserType>,1,</UserType>
      <DeployStatus>2</DeployStatus>
    </DesignAppMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployAppMetadata>
