<?xml version="1.0" encoding="UTF-8"?>

<DeployAppMetadata>
  <Multilanguage>false</Multilanguage>
  <MasterId>3DHP9AXYYV5H</MasterId>
  <Id>3DHP9AXYYV5H</Id>
  <DesignMetas>
    <DesignAppMeta>
      <DevType>0</DevType>
      <AppVersion>5.0.001.0</AppVersion>
      <Modifier>1760310820044270594</Modifier>
      <DataXml>
        <AppMetadata>
          <DevType>0</DevType>
          <AppFunctionPackets>
            <AppFunctionPacketElement>
              <Number>MainPage</Number>
              <Name>首页</Name>
              <Description/>
              <Id>3DHP9B2N/R0E</Id>
              <Leaf>0</Leaf>
              <ParentId/>
              <Seq>1</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>leaderSelfService</Number>
              <Name>APP领导自助</Name>
              <Description/>
              <Id>3DHQANZ63RRN</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>2</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>leaderSelfServicePC</Number>
              <Name>PC领导自助</Name>
              <Description/>
              <Id>3ED/F7IABBC9</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>3</Seq>
            </AppFunctionPacketElement>
          </AppFunctionPackets>
          <AppMenus>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>2c63e459cb</Number>
              <FormName>人员分析</FormName>
              <FormNumber>tdkw_personanalysis</FormNumber>
              <Parameter/>
              <Id>1742823408351075328</Id>
              <Seq>1</Seq>
              <FormId>3C7PCKJL6YGC</FormId>
              <ParameterType>FormShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj3_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>3DHP9AXYYV5H</ParentId>
              <VectorImage>kdfont kdfont-tongyongtubiao5</VectorImage>
              <Name>人员分析</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>9a2f1b5a6b</Number>
              <FormName>入职分析</FormName>
              <FormNumber>tdkw_onboardinganalysis</FormNumber>
              <Parameter/>
              <Id>1742831364610220032</Id>
              <Seq>2</Seq>
              <FormId>3D41U0FBVWXB</FormId>
              <ParameterType>FormShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj2_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>3DHP9AXYYV5H</ParentId>
              <VectorImage>kdfont kdfont-tongyongtubiao4</VectorImage>
              <Name>入职分析</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>9449c442b6</Number>
              <FormName>离职分析</FormName>
              <FormNumber>tdkw_offroadanalysis</FormNumber>
              <Parameter/>
              <Id>1742831448152366080</Id>
              <Seq>3</Seq>
              <FormId>3DH3=WBE/P2W</FormId>
              <ParameterType>FormShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>3DHP9AXYYV5H</ParentId>
              <VectorImage>kdfont kdfont-tongyongtubiao3</VectorImage>
              <Name>离职分析</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Caption>帮助中心</Caption>
              <Description>帮助中心</Description>
              <FormName>应用入门中心</FormName>
              <FormNumber>bas_appstarted</FormNumber>
              <Parameter>{"caption":{"zh_CN":"帮助中心"}}</Parameter>
              <Id>3G1P+XG3T4O#hpce</Id>
              <Seq>32766</Seq>
              <FormId>/WXHVRP15OWF</FormId>
              <IconShortcut>/icons/pc/entrance/helpcentre.png</IconShortcut>
              <Visible>0</Visible>
              <ParentId>3DHP9AXYYV5H</ParentId>
              <VectorImage>kdfont kdfont-tishixinxi_l</VectorImage>
              <Name>帮助中心</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
          </AppMenus>
          <Isv>tdkw</Isv>
          <Number>tdkw_appauthorityleader</Number>
          <Id>3DHP9AXYYV5H</Id>
          <BizCloudID>18Y2T5WS5AFV</BizCloudID>
          <ParentId/>
          <MasterId/>
          <AppElement>
            <AppElement>
              <MainFormNumber>tdkw_appauthorityleader_apphome</MainFormNumber>
              <Description>这是一个新的应用</Description>
              <DbRoute>secd</DbRoute>
              <OpenType>0</OpenType>
              <AllUserApp>0</AllUserApp>
              <Number>tdkw_appauthorityleader</Number>
              <Id>3DHP9AXYYV5H</Id>
              <Seq>266</Seq>
              <MainFormType>0</MainFormType>
              <DependencyID/>
              <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
              <OrgFunc/>
              <Visible>0</Visible>
              <Dependency/>
              <HelpURL/>
              <Label/>
              <MainFormName>应用权限领导_应用首页</MainFormName>
              <Version>5.0.001.0</Version>
              <BackImage/>
              <HomeURL/>
              <MainFormID>3DHP9EA8SNM+</MainFormID>
              <Name>应用权限领导</Name>
              <SimpleNumber/>
              <UserType>,1,</UserType>
              <DeployStatus>2</DeployStatus>
            </AppElement>
          </AppElement>
          <InheritPath/>
        </AppMetadata>
      </DataXml>
      <Description></Description>
      <DbRoute>secd</DbRoute>
      <Isv>tdkw</Isv>
      <OpenType>0</OpenType>
      <AllUserApp>0</AllUserApp>
      <Number>tdkw_appauthorityleader</Number>
      <IndustryId>0</IndustryId>
      <Id>3DHP9AXYYV5H</Id>
      <Seq>266</Seq>
      <CreateDate>1688472634844</CreateDate>
      <MainFormType>0</MainFormType>
      <BizCloudID>18Y2T5WS5AFV</BizCloudID>
      <DependencyID></DependencyID>
      <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
      <OrgFunc></OrgFunc>
      <Visible>0</Visible>
      <ModifyDate>1698378911993</ModifyDate>
      <Dependency></Dependency>
      <HelpURL></HelpURL>
      <Label></Label>
      <ModelType>AppModel</ModelType>
      <MainFormName>应用权限领导_应用首页</MainFormName>
      <ParentId></ParentId>
      <BackImage></BackImage>
      <HomeURL></HomeURL>
      <MasterId></MasterId>
      <Creater>1703109885295605760</Creater>
      <MainFormID>3DHP9EA8SNM+</MainFormID>
      <SimpleNumber></SimpleNumber>
      <InheritPath></InheritPath>
      <RefAppId></RefAppId>
      <UserType>,1,</UserType>
      <DeployStatus>2</DeployStatus>
    </DesignAppMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployAppMetadata>
