<?xml version="1.0" encoding="UTF-8"?>

<DeployAppMetadata>
  <Multilanguage>false</Multilanguage>
  <MasterId>0QO140ANVBBZ</MasterId>
  <Id>4HRMD0/JF+G3</Id>
  <DesignMetas>
    <DesignAppMeta>
      <DevType>2</DevType>
      <AppVersion>1.5.0</AppVersion>
      <Modifier>2027699484829418496</Modifier>
      <DataXml>
        <AppMetadata>
          <DevType>2</DevType>
          <Isv>tdkw</Isv>
          <Number>tdkw_hrpi_ext</Number>
          <Id>4HRMD0/JF+G3</Id>
          <ParentId>0QO140ANVBBZ</ParentId>
          <MasterId>0QO140ANVBBZ</MasterId>
          <AppElement>
            <AppElement>
              <Number>tdkw_hrpi_ext</Number>
              <Id>4HRMD0/JF+G3</Id>
              <Version>1.5.0</Version>
              <UserType>,1,</UserType>
            </AppElement>
          </AppElement>
          <InheritPath>0QO140ANVBBZ</InheritPath>
        </AppMetadata>
      </DataXml>
      <Description></Description>
      <DbRoute>hr</DbRoute>
      <Isv>tdkw</Isv>
      <OpenType>0</OpenType>
      <AllUserApp>0</AllUserApp>
      <Number>tdkw_hrpi_ext</Number>
      <IndustryId>0</IndustryId>
      <Id>4HRMD0/JF+G3</Id>
      <Seq>30</Seq>
      <CreateDate>1730447338350</CreateDate>
      <MainFormType>0</MainFormType>
      <BizCloudID>0PEIU203SX4Y</BizCloudID>
      <DependencyID></DependencyID>
      <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
      <OrgFunc></OrgFunc>
      <Visible>1</Visible>
      <Dependency></Dependency>
      <HelpURL></HelpURL>
      <Label></Label>
      <ModelType>AppModel</ModelType>
      <MainFormName>员工信息中心_应用首页</MainFormName>
      <ParentId>0QO140ANVBBZ</ParentId>
      <BackImage></BackImage>
      <HomeURL></HomeURL>
      <MasterId>0QO140ANVBBZ</MasterId>
      <Creater>2027699484829418496</Creater>
      <MainFormID>0QO143E56F/K</MainFormID>
      <SimpleNumber></SimpleNumber>
      <InheritPath>0QO140ANVBBZ</InheritPath>
      <RefAppId></RefAppId>
      <UserType>,1,</UserType>
      <DeployStatus>2</DeployStatus>
    </DesignAppMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployAppMetadata>
