EXEC p_AlterColumn 'T_CEA_ASSESSOBJ', 'FCALSCORE', 'DECIMAL(23, 6)', 'NOT NULL', '0100', '''0''';

EXEC p_AlterColumn 'T_CEA_ASSESSOBJ', 'FMODSCORE', 'DECIMAL(23, 6)', 'NOT NULL', '0100', '''0''';

EXEC p_AlterColumn 'T_CEA_ASSESSFORMROWFIX', 'FINDICATORDESC', 'NVARCHAR(1000)', 'NOT NULL', '0100', ''' ''';
