EXEC P_ALTERPK 'PK_CEA_ASSESSACTIVITY', 'T_CEA_ASSESSACTIVITY', 'FID', '1';

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_ASSESSACTIVITY' AND KSQL_INDNAME = 'IDX_CEA_ASSESSACTIVITY_NUM') CREATE INDEX IDX_CEA_ASSESSACTIVITY_NUM ON T_CEA_ASSESSACTIVITY ( FNUMBER );

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_ASSESSACTIVITY' AND KSQL_INDNAME = 'IDX_CEA_ASSESSACTIVITY_NAME') CREATE INDEX IDX_CEA_ASSESSACTIVITY_NAME ON T_CEA_ASSESSACTIVITY ( FNAME );


EXEC P_ALTERPK 'PK_CEA_ASSESSACTIVITY_L', 'T_CEA_ASSESSACTIVITY_L', 'FPKID', '1';

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_ASSESSACTIVITY_L' AND KSQL_INDNAME = 'IDX_CEA_ASSESSACTIVITY_L') CREATE INDEX IDX_CEA_ASSESSACTIVITY_L ON T_CEA_ASSESSACTIVITY_L ( FID ,FLOCALEID );

EXEC P_ALTERPK 'PK_CEA_ASSESSFORMFIX', 'T_CEA_ASSESSFORMFIX', 'FID', '1';

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_ASSESSFORMFIX' AND KSQL_INDNAME = 'IDX_CEA_ASSESSFORMFIX_DIMGROUP') CREATE INDEX IDX_CEA_ASSESSFORMFIX_DIMGROUP ON T_CEA_ASSESSFORMFIX ( FDIMGROUPID );

EXEC P_ALTERPK 'PK_CEA_ASSESSFORMFIX_L', 'T_CEA_ASSESSFORMFIX_L', 'FPKID', '1';

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_ASSESSFORMFIX_L' AND KSQL_INDNAME = 'IDX_CEA_ASSESSFORMFIX_L') CREATE INDEX IDX_CEA_ASSESSFORMFIX_L ON T_CEA_ASSESSFORMFIX_L ( FID ,FLOCALEID );

EXEC P_ALTERPK 'PK_CEA_ASSESSFORMROWFIX', 'T_CEA_ASSESSFORMROWFIX', 'FENTRYID', '1';

EXEC P_ALTERPK 'PK_CEA_ASSESSFORMROWFIX_L', 'T_CEA_ASSESSFORMROWFIX_L', 'FPKID', '1';

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_ASSESSFORMROWFIX_L' AND KSQL_INDNAME = 'IDX_CEA_ASSESSFORMROWFIX_L') CREATE INDEX IDX_CEA_ASSESSFORMROWFIX_L ON T_CEA_ASSESSFORMROWFIX_L ( FENTRYID ,FLOCALEID );

EXEC P_ALTERPK 'PK_CEA_ASSESSOBJ', 'T_CEA_ASSESSOBJ', 'FID', '1';

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_ASSESSOBJ' AND KSQL_INDNAME = 'IDX_CEA_ASSESSOBJ_ACT') CREATE INDEX IDX_CEA_ASSESSOBJ_ACT ON T_CEA_ASSESSOBJ ( FASSESSACTID );

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_ASSESSOBJ' AND KSQL_INDNAME = 'IDX_CEA_ASSESSOBJ_GROUP') CREATE INDEX IDX_CEA_ASSESSOBJ_GROUP ON T_CEA_ASSESSOBJ ( FDIMGROUPID );

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_ASSESSOBJ' AND KSQL_INDNAME = 'IDX_CEA_ASSESSOBJ_STATUS') CREATE INDEX IDX_CEA_ASSESSOBJ_STATUS ON T_CEA_ASSESSOBJ ( FASSESSTAUS );

EXEC P_ALTERPK 'PK_CEA_ASSESSOBJ_L', 'T_CEA_ASSESSOBJ_L', 'FPKID', '1';

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_ASSESSOBJ_L' AND KSQL_INDNAME = 'IDX_CEA_ASSESSOBJ_L') CREATE INDEX IDX_CEA_ASSESSOBJ_L ON T_CEA_ASSESSOBJ_L ( FID ,FLOCALEID );

EXEC P_ALTERPK 'PK_CEA_ASSESSTASK', 'T_CEA_ASSESSTASK', 'FID', '1';

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_ASSESSTASK' AND KSQL_INDNAME = 'IDX_CEA_ASSESSTASK_ASSOBJ') CREATE INDEX IDX_CEA_ASSESSTASK_ASSOBJ ON T_CEA_ASSESSTASK ( FASSESSOBJID );

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_ASSESSTASK' AND KSQL_INDNAME = 'IDX_CEA_ASSESSTASK_EVALDIM') CREATE INDEX IDX_CEA_ASSESSTASK_EVALDIM ON T_CEA_ASSESSTASK ( FEVALDIMID );

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_ASSESSTASK' AND KSQL_INDNAME = 'IDX_CEA_ASSESSTASK_ACT') CREATE INDEX IDX_CEA_ASSESSTASK_ACT ON T_CEA_ASSESSTASK ( FASSESSACTID );

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_ASSESSTASK' AND KSQL_INDNAME = 'IDX_CEA_ASSESSTASK_STATUS') CREATE INDEX IDX_CEA_ASSESSTASK_STATUS ON T_CEA_ASSESSTASK ( FASSESTASKSTATUS );

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_ASSESSTASK' AND KSQL_INDNAME = 'IDX_CEA_ASSESSTASK_DIMASSER') CREATE INDEX IDX_CEA_ASSESSTASK_DIMASSER ON T_CEA_ASSESSTASK ( FDIMASSESSERID );

EXEC P_ALTERPK 'PK_CEA_ASSESSTASK_L', 'T_CEA_ASSESSTASK_L', 'FPKID', '1';

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_ASSESSTASK_L' AND KSQL_INDNAME = 'IDX_CEA_ASSESSTASK_L') CREATE INDEX IDX_CEA_ASSESSTASK_L ON T_CEA_ASSESSTASK_L ( FID ,FLOCALEID );

EXEC P_ALTERPK 'PK_CEA_ASSOBJSCOITEMINS', 'T_CEA_ASSOBJSCOITEMINS', 'FID', '1';

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_ASSOBJSCOITEMINS' AND KSQL_INDNAME = 'IDX_CEA_ASSOBJSCOITEMINS_ASSOBJ') CREATE INDEX IDX_CEA_ASSOBJSCOITEMINS_ASSOBJ ON T_CEA_ASSOBJSCOITEMINS ( FFASSESSOBJID );

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_ASSOBJSCOITEMINS' AND KSQL_INDNAME = 'IDX_CEA_ASSOBJSCOITEMINS_FORMROW') CREATE INDEX IDX_CEA_ASSOBJSCOITEMINS_FORMROW ON T_CEA_ASSOBJSCOITEMINS ( FASSESSFORMROWID );

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_ASSOBJSCOITEMINS' AND KSQL_INDNAME = 'IDX_CEA_ASSOBJSCOITEMINS_ENTRY') CREATE INDEX IDX_CEA_ASSOBJSCOITEMINS_ENTRY ON T_CEA_ASSOBJSCOITEMINS ( FENTRYID );

EXEC P_ALTERPK 'PK_CEA_ASSOBJSCOITEMINS_L', 'T_CEA_ASSOBJSCOITEMINS_L', 'FPKID', '1';

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_ASSOBJSCOITEMINS_L' AND KSQL_INDNAME = 'IDX_CEA_ASSOBJSCOITEMINS_L') CREATE INDEX IDX_CEA_ASSOBJSCOITEMINS_L ON T_CEA_ASSOBJSCOITEMINS_L ( FENTRYID, FLOCALEID );

EXEC P_ALTERPK 'PK_CEA_DIMASSESSER', 'T_CEA_DIMASSESSER', 'FENTRYID', '1';

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_DIMASSESSER' AND KSQL_INDNAME = 'IDX_CEA_DIMASSESSER_EVALDIM') CREATE INDEX IDX_CEA_DIMASSESSER_EVALDIM ON T_CEA_DIMASSESSER ( FEVALDIMID );

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_DIMASSESSER' AND KSQL_INDNAME = 'IDX_CEA_DIMASSESSER_GROUP') CREATE INDEX IDX_CEA_DIMASSESSER_GROUP ON T_CEA_DIMASSESSER ( FGROUPDIMID );

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_DIMASSESSER' AND KSQL_INDNAME = 'IDX_CEA_DIMASSESSER_ASSOBJ') CREATE INDEX IDX_CEA_DIMASSESSER_ASSOBJ ON T_CEA_DIMASSESSER ( FASSOBJID );

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_DIMASSESSER' AND KSQL_INDNAME = 'IDX_CEA_DIMASSESSER_STATUS') CREATE INDEX IDX_CEA_DIMASSESSER_STATUS ON T_CEA_DIMASSESSER ( FASSESSTATUS );

EXEC P_ALTERPK 'PK_CEA_DIMSETTING', 'T_CEA_DIMSETTING', 'FENTRYID', '1';

EXEC P_ALTERPK 'PK_CEA_DIMSETTING_L', 'T_CEA_DIMSETTING_L', 'FPKID', '1';

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_DIMSETTING_L' AND KSQL_INDNAME = 'IDX_CEA_DIMSETTING_L') CREATE INDEX IDX_CEA_DIMSETTING_L ON T_CEA_DIMSETTING_L ( FENTRYID, FLOCALEID );

EXEC P_ALTERPK 'PK_CEA_EVALDIMSETTING', 'T_CEA_EVALDIMSETTING', 'FID', '1';

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_EVALDIMSETTING' AND KSQL_INDNAME = 'IDX_CEA_EVALDIMSETTING_ENTRY') CREATE INDEX IDX_CEA_EVALDIMSETTING_ENTRY ON T_CEA_EVALDIMSETTING ( FENTRYID );

EXEC P_ALTERPK 'PK_CEA_EVALDIMSETTING_L', 'T_CEA_EVALDIMSETTING_L', 'FPKID', '1';

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_EVALDIMSETTING_L' AND KSQL_INDNAME = 'IDX_CEA_EVALDIMSETTING_L') CREATE INDEX IDX_CEA_EVALDIMSETTING_L ON T_CEA_EVALDIMSETTING_L ( FID, FLOCALEID );

EXEC P_ALTERPK 'PK_CEA_ASSERSEEKCONF', 'T_CEA_ASSERSEEKCONF', 'FID', '1';

EXEC P_ALTERPK 'PK_CEA_ASSERSEEKCONF_L', 'T_CEA_ASSERSEEKCONF_L', 'FPKID', '1';

IF NOT EXISTS (SELECT 1 FROM KSQL_INDEXES WHERE KSQL_TABNAME = 'T_CEA_ASSERSEEKCONF_L' AND KSQL_INDNAME = 'IDX_CEA_ASSERSEEKCONF_L') CREATE INDEX IDX_CEA_ASSERSEEKCONF_L ON T_CEA_ASSERSEEKCONF_L ( FID, FLOCALEID );

EXEC P_ALTERPK 'PK_CEA_ASSERSEEKCONFENTRY', 'T_CEA_ASSERSEEKCONFENTRY', 'FENTRYID', '1';

