IF NOT EXISTS (SELECT 1 FROM KSQL_USERTABLES WHERE KSQL_TABNAME = 'T_CEA_ASSESSACTIVITY')
CREATE TABLE T_CEA_ASSESSACTIVITY (
	FID BIGINT DEFAULT 0 NOT NULL,
	FNUMBER NVARCHAR(80) DEFAULT ' ' NOT NULL,
	FNAME NVARCHAR(100) DEFAULT ' ' NOT NULL,
	FSTATUS VARCHAR(2) DEFAULT 'C' NOT NULL,
	FCREATORID BIGINT DEFAULT 0 NOT NULL,
	FMODIFIERID BIGINT DEFAULT 0 NOT NULL,
	FENABLE VARCHAR(2) DEFAULT '1' NOT NULL,
	FCREATETIME DATETIME,
	FMODIFYTIME DATETIME,
	FMASTERID BIGINT DEFAULT 0 NOT NULL,
	FREALORANOYMOUS VARCHAR(2) DEFAULT ' ' NOT NULL,
	FPERIODSTARTDATE DATETIME,
	FPERIODENDDATE DATETIME,
	FORGID BIGINT DEFAULT 0 NOT NULL,
	FADMINORGID BIGINT DEFAULT 0 NOT NULL,
	FSCORESYSTEMMAP VARCHAR(2) DEFAULT ' ' NOT NULL,
	FSCORESYSTEMID BIGINT DEFAULT 0 NOT NULL,
	FMPNUMACCURACY VARCHAR(2) DEFAULT ' ' NOT NULL,
	FMPSCALETYPE VARCHAR(2) DEFAULT ' ' NOT NULL,
	FACTIVITYSTATUS VARCHAR(2) DEFAULT ' ' NOT NULL,
	FBILLSTATUS VARCHAR(2) DEFAULT ' ' NOT NULL,
	FINTROCONTENT NVARCHAR(1000) DEFAULT ' ' NOT NULL,
	FASSESSORCOUNT INT DEFAULT 0 NOT NULL
);

IF NOT EXISTS (SELECT 1 FROM KSQL_USERTABLES WHERE KSQL_TABNAME = 'T_CEA_ASSESSACTIVITY_L')
CREATE TABLE T_CEA_ASSESSACTIVITY_L (
	FPKID VARCHAR(18) DEFAULT ' ' NOT NULL,
	FID BIGINT DEFAULT 0 NOT NULL,
	FLOCALEID VARCHAR(10) DEFAULT ' ' NOT NULL,
	FNAME NVARCHAR(255) DEFAULT ' ' NOT NULL
);

IF NOT EXISTS (SELECT 1 FROM KSQL_USERTABLES WHERE KSQL_TABNAME = 'T_CEA_ASSESSFORMFIX')
CREATE TABLE T_CEA_ASSESSFORMFIX (
	FID BIGINT DEFAULT 0 NOT NULL,
	FNUMBER NVARCHAR(80) DEFAULT ' ' NOT NULL,
	FNAME NVARCHAR(100) DEFAULT ' ' NOT NULL,
	FSTATUS VARCHAR(2) DEFAULT 'C' NOT NULL,
	FCREATORID BIGINT DEFAULT 0 NOT NULL,
	FMODIFIERID BIGINT DEFAULT 0 NOT NULL,
	FENABLE VARCHAR(2) DEFAULT '1' NOT NULL,
	FCREATETIME DATETIME,
	FMODIFYTIME DATETIME,
	FMASTERID BIGINT DEFAULT 0 NOT NULL,
	FASSFORMTYPE VARCHAR(2) DEFAULT ' ' NOT NULL,
	FLEVELMAPNUMBER NVARCHAR(80) DEFAULT ' ' NOT NULL,
	FDIMGROUPID BIGINT DEFAULT 0 NOT NULL
);

IF NOT EXISTS (SELECT 1 FROM KSQL_USERTABLES WHERE KSQL_TABNAME = 'T_CEA_ASSESSFORMFIX_L')
CREATE TABLE T_CEA_ASSESSFORMFIX_L (
	FPKID VARCHAR(18) DEFAULT ' ' NOT NULL,
	FID BIGINT DEFAULT 0 NOT NULL,
	FLOCALEID VARCHAR(10) DEFAULT ' ' NOT NULL,
	FNAME NVARCHAR(255) DEFAULT ' ' NOT NULL
);

IF NOT EXISTS (SELECT 1 FROM KSQL_USERTABLES WHERE KSQL_TABNAME = 'T_CEA_ASSESSFORMROWFIX')
CREATE TABLE T_CEA_ASSESSFORMROWFIX (
	FENTRYID BIGINT DEFAULT 0 NOT NULL,
	FNUMBER NVARCHAR(80) DEFAULT ' ' NOT NULL,
	FNAME NVARCHAR(100) DEFAULT ' ' NOT NULL,
	FSTATUS VARCHAR(2) DEFAULT 'C' NOT NULL,
	FCREATORID BIGINT DEFAULT 0 NOT NULL,
	FMODIFIERID BIGINT DEFAULT 0 NOT NULL,
	FENABLE VARCHAR(2) DEFAULT '1' NOT NULL,
	FCREATETIME DATETIME,
	FMODIFYTIME DATETIME,
	FMASTERID BIGINT DEFAULT 0 NOT NULL,
	FINDICATORNAME NVARCHAR(100) DEFAULT ' ' NOT NULL,
	FINDICATORDESC NVARCHAR(255) DEFAULT ' ' NOT NULL,
	FINDICATORINDEX INT DEFAULT 0 NOT NULL,
	FRESPONSIBILITY NVARCHAR(100) DEFAULT ' ' NOT NULL,
	FID BIGINT DEFAULT 0 NOT NULL,
	FSEQ INT DEFAULT 0 NOT NULL,
	FINDICATORWEIGHT DECIMAL(23, 2) DEFAULT 0 NOT NULL,
	FINDICATORSCORE INT DEFAULT 0 NOT NULL
);

IF NOT EXISTS (SELECT 1 FROM KSQL_USERTABLES WHERE KSQL_TABNAME = 'T_CEA_ASSESSFORMROWFIX_L')
CREATE TABLE T_CEA_ASSESSFORMROWFIX_L (
	FPKID VARCHAR(18) DEFAULT ' ' NOT NULL,
	FENTRYID BIGINT DEFAULT 0 NOT NULL,
	FLOCALEID VARCHAR(10) DEFAULT ' ' NOT NULL,
	FNAME NVARCHAR(255) DEFAULT ' ' NOT NULL
);

IF NOT EXISTS (SELECT 1 FROM KSQL_USERTABLES WHERE KSQL_TABNAME = 'T_CEA_ASSESSOBJ')
CREATE TABLE T_CEA_ASSESSOBJ (
	FID BIGINT DEFAULT 0 NOT NULL,
	FPERSONID BIGINT DEFAULT 0 NOT NULL,
	FEMPLOYEEID BIGINT DEFAULT 0 NOT NULL,
	FPERFILEVID BIGINT DEFAULT 0 NOT NULL,
	FPERFILEID BIGINT DEFAULT 0 NOT NULL,
	FAFFILIATEADMINORGID BIGINT DEFAULT 0 NOT NULL,
	FEMPPOSORGRELID BIGINT DEFAULT 0 NOT NULL,
	FPERFORGID BIGINT DEFAULT 0 NOT NULL,
	FASSESSACTID BIGINT DEFAULT 0 NOT NULL,
	FASSESSTAUS VARCHAR(2) DEFAULT ' ' NOT NULL,
	FDIMGROUPID BIGINT DEFAULT 0 NOT NULL,
	FCALSCORE DECIMAL(23, 2) DEFAULT 0 NOT NULL,
	FMODSCORE DECIMAL(23, 2) DEFAULT 0 NOT NULL,
	FNUMBER NVARCHAR(80) DEFAULT ' ' NOT NULL,
	FNAME NVARCHAR(100) DEFAULT ' ' NOT NULL,
	FSTATUS VARCHAR(2) DEFAULT 'C' NOT NULL,
	FCREATORID BIGINT DEFAULT 0 NOT NULL,
	FMODIFIERID BIGINT DEFAULT 0 NOT NULL,
	FENABLE VARCHAR(2) DEFAULT '1' NOT NULL,
	FCREATETIME DATETIME,
	FMODIFYTIME DATETIME,
	FMASTERID BIGINT DEFAULT 0 NOT NULL,
	FADDINTIME DATETIME,
	FOVERTIME DATETIME,
	FSUMMARY NVARCHAR(255) DEFAULT ' ' NOT NULL,
	FSUMLEVEL NVARCHAR(50) DEFAULT ' ' NOT NULL
);

IF NOT EXISTS (SELECT 1 FROM KSQL_USERTABLES WHERE KSQL_TABNAME = 'T_CEA_ASSESSOBJ_L')
CREATE TABLE T_CEA_ASSESSOBJ_L (
	FPKID VARCHAR(18) DEFAULT ' ' NOT NULL,
	FID BIGINT DEFAULT 0 NOT NULL,
	FLOCALEID VARCHAR(10) DEFAULT ' ' NOT NULL,
	FNAME NVARCHAR(255) DEFAULT ' ' NOT NULL
);

IF NOT EXISTS (SELECT 1 FROM KSQL_USERTABLES WHERE KSQL_TABNAME = 'T_CEA_ASSESSTASK')
CREATE TABLE T_CEA_ASSESSTASK (
	FID BIGINT DEFAULT 0 NOT NULL,
	FNUMBER NVARCHAR(80) DEFAULT ' ' NOT NULL,
	FNAME NVARCHAR(100) DEFAULT ' ' NOT NULL,
	FSTATUS VARCHAR(2) DEFAULT 'C' NOT NULL,
	FCREATORID BIGINT DEFAULT 0 NOT NULL,
	FMODIFIERID BIGINT DEFAULT 0 NOT NULL,
	FENABLE VARCHAR(2) DEFAULT '1' NOT NULL,
	FCREATETIME DATETIME,
	FMODIFYTIME DATETIME,
	FMASTERID BIGINT DEFAULT 0 NOT NULL,
	FASSESSOBJID BIGINT DEFAULT 0 NOT NULL,
	FEVALDIMID BIGINT DEFAULT 0 NOT NULL,
	FASSESSACTID BIGINT DEFAULT 0 NOT NULL,
	FPERFILEID BIGINT DEFAULT 0 NOT NULL,
	FPERSONID BIGINT DEFAULT 0 NOT NULL,
	FASSESTASKSTATUS VARCHAR(2) DEFAULT ' ' NOT NULL,
	FDIMGROUPID BIGINT DEFAULT 0 NOT NULL,
	FDIMASSESSERID BIGINT DEFAULT 0 NOT NULL,
	FASSESSERPERSONID BIGINT DEFAULT 0 NOT NULL,
	FTASKARRIVALTIME DATETIME,
	FTASKCOMPLETIONTIME DATETIME,
	FLATESTCHANGETIME DATETIME
);

IF NOT EXISTS (SELECT 1 FROM KSQL_USERTABLES WHERE KSQL_TABNAME = 'T_CEA_ASSESSTASK_L')
CREATE TABLE T_CEA_ASSESSTASK_L (
	FPKID VARCHAR(18) DEFAULT ' ' NOT NULL,
	FID BIGINT DEFAULT 0 NOT NULL,
	FLOCALEID VARCHAR(10) DEFAULT ' ' NOT NULL,
	FNAME NVARCHAR(255) DEFAULT ' ' NOT NULL
);

IF NOT EXISTS (SELECT 1 FROM KSQL_USERTABLES WHERE KSQL_TABNAME = 'T_CEA_ASSOBJSCOITEMINS')
CREATE TABLE T_CEA_ASSOBJSCOITEMINS (
	FID BIGINT DEFAULT 0 NOT NULL,
	FNUMBER NVARCHAR(80) DEFAULT ' ' NOT NULL,
	FNAME NVARCHAR(100) DEFAULT ' ' NOT NULL,
	FSTATUS VARCHAR(2) DEFAULT 'C' NOT NULL,
	FCREATORID BIGINT DEFAULT 0 NOT NULL,
	FMODIFIERID BIGINT DEFAULT 0 NOT NULL,
	FENABLE VARCHAR(2) DEFAULT '1' NOT NULL,
	FCREATETIME DATETIME,
	FMODIFYTIME DATETIME,
	FMASTERID BIGINT DEFAULT 0 NOT NULL,
	FFASSESSOBJID BIGINT DEFAULT 0 NOT NULL,
	FASSESSFORMROWID BIGINT DEFAULT 0 NOT NULL,
	FINDICATORWEIGHT DECIMAL(23, 2) DEFAULT 0 NOT NULL,
	FSCOREVALUE VARCHAR(50) DEFAULT ' ' NOT NULL,
	FENTRYID BIGINT DEFAULT 0 NOT NULL,
	FSEQ INT DEFAULT 0 NOT NULL,
	FLEVELSEQ INT DEFAULT 0 NOT NULL,
	FLEVELSCORE VARCHAR(50) DEFAULT ' ' NOT NULL,
	FLEVELENTRY VARCHAR(50) DEFAULT ' ' NOT NULL
);

IF NOT EXISTS (SELECT 1 FROM KSQL_USERTABLES WHERE KSQL_TABNAME = 'T_CEA_ASSOBJSCOITEMINS_L')
CREATE TABLE T_CEA_ASSOBJSCOITEMINS_L (
	FPKID VARCHAR(18) DEFAULT ' ' NOT NULL,
	FENTRYID BIGINT DEFAULT 0 NOT NULL,
	FLOCALEID VARCHAR(10) DEFAULT ' ' NOT NULL,
	FNAME NVARCHAR(255) DEFAULT ' ' NOT NULL,
	FID BIGINT DEFAULT 0 NOT NULL
);

IF NOT EXISTS (SELECT 1 FROM KSQL_USERTABLES WHERE KSQL_TABNAME = 'T_CEA_DIMASSESSER')
CREATE TABLE T_CEA_DIMASSESSER (
	FENTRYID BIGINT DEFAULT 0 NOT NULL,
	FDIMWEIGHT DECIMAL(23, 2) DEFAULT 0 NOT NULL,
	FASSESSERID BIGINT DEFAULT 0 NOT NULL,
	FEVALDIMID BIGINT DEFAULT 0 NOT NULL,
	FID BIGINT DEFAULT 0 NOT NULL,
	FSEQ INT DEFAULT 0 NOT NULL,
	FASSESSTATUS VARCHAR(2) DEFAULT ' ' NOT NULL,
	FGROUPDIMID BIGINT DEFAULT 0 NOT NULL,
	FASSOBJID BIGINT DEFAULT 0 NOT NULL,
	FDIMNAME NVARCHAR(100) DEFAULT ' ' NOT NULL
);

IF NOT EXISTS (SELECT 1 FROM KSQL_USERTABLES WHERE KSQL_TABNAME = 'T_CEA_DIMSETTING')
CREATE TABLE T_CEA_DIMSETTING (
	FENTRYID BIGINT DEFAULT 0 NOT NULL,
	FDESCRIPTION NVARCHAR(255) DEFAULT ' ' NOT NULL,
	FDIMENSION VARCHAR(2) DEFAULT ' ' NOT NULL,
	FID BIGINT DEFAULT 0 NOT NULL,
	FSEQ INT DEFAULT 0 NOT NULL,
	FGROUPDIMNAME NVARCHAR(100) DEFAULT ' ' NOT NULL,
	FASSESSFORMID BIGINT DEFAULT 0 NOT NULL,
	FGROUPINDEX INT DEFAULT 0 NOT NULL
);

IF NOT EXISTS (SELECT 1 FROM KSQL_USERTABLES WHERE KSQL_TABNAME = 'T_CEA_DIMSETTING_L')
CREATE TABLE T_CEA_DIMSETTING_L (
	FPKID VARCHAR(18) DEFAULT ' ' NOT NULL,
	FENTRYID BIGINT DEFAULT 0 NOT NULL,
	FLOCALEID VARCHAR(10) DEFAULT ' ' NOT NULL,
	FNAME NVARCHAR(255) DEFAULT ' ' NOT NULL
);

IF NOT EXISTS (SELECT 1 FROM KSQL_USERTABLES WHERE KSQL_TABNAME = 'T_CEA_EVALDIMSETTING')
CREATE TABLE T_CEA_EVALDIMSETTING (
	FENTRYID BIGINT DEFAULT 0 NOT NULL,
	FID BIGINT DEFAULT 0 NOT NULL,
	FSEQ INT DEFAULT 0 NOT NULL,
	FDIMINDEX INT DEFAULT 0 NOT NULL,
	FDIMNAME NVARCHAR(100) DEFAULT ' ' NOT NULL,
	FDIMWEIGHT DECIMAL(23, 2) DEFAULT 0 NOT NULL,
	FNUMBER NVARCHAR(80) DEFAULT ' ' NOT NULL,
	FNAME NVARCHAR(100) DEFAULT ' ' NOT NULL,
	FSTATUS VARCHAR(2) DEFAULT 'C' NOT NULL,
	FCREATORID BIGINT DEFAULT 0 NOT NULL,
	FMODIFIERID BIGINT DEFAULT 0 NOT NULL,
	FENABLE VARCHAR(2) DEFAULT '1' NOT NULL,
	FCREATETIME DATETIME,
	FMODIFYTIME DATETIME,
	FMASTERID BIGINT DEFAULT 0 NOT NULL,
	FEVALROLEID BIGINT DEFAULT 0 NOT NULL
);

IF NOT EXISTS (SELECT 1 FROM KSQL_USERTABLES WHERE KSQL_TABNAME = 'T_CEA_EVALDIMSETTING_L')
CREATE TABLE T_CEA_EVALDIMSETTING_L (
	FPKID VARCHAR(18) DEFAULT ' ' NOT NULL,
	FID BIGINT DEFAULT 0 NOT NULL,
	FLOCALEID VARCHAR(10) DEFAULT ' ' NOT NULL,
	FNAME NVARCHAR(255) DEFAULT ' ' NOT NULL
);
	
IF NOT EXISTS (SELECT 1 FROM KSQL_USERTABLES WHERE KSQL_TABNAME = 'T_CEA_ASSERSEEKCONF')
CREATE TABLE T_CEA_ASSERSEEKCONF (
	FID BIGINT DEFAULT 0 NOT NULL,
	FNUMBER NVARCHAR(80) DEFAULT ' ' NOT NULL,
	FNAME NVARCHAR(100) DEFAULT ' ' NOT NULL,
	FSTATUS VARCHAR(2) DEFAULT 'C' NOT NULL,
	FCREATORID BIGINT DEFAULT 0 NOT NULL,
	FMODIFIERID BIGINT DEFAULT 0 NOT NULL,
	FENABLE VARCHAR(2) DEFAULT '1' NOT NULL,
	FCREATETIME DATETIME,
	FMODIFYTIME DATETIME,
	FMASTERID BIGINT DEFAULT 0 NOT NULL,
	FSEEKTYPE VARCHAR(2) DEFAULT ' ' NOT NULL
);
	
IF NOT EXISTS (SELECT 1 FROM KSQL_USERTABLES WHERE KSQL_TABNAME = 'T_CEA_ASSERSEEKCONF_L')
CREATE TABLE T_CEA_ASSERSEEKCONF_L (
	FPKID VARCHAR(18) DEFAULT ' ' NOT NULL,
	FID BIGINT DEFAULT 0 NOT NULL,
	FLOCALEID VARCHAR(10) DEFAULT ' ' NOT NULL,
	FNAME NVARCHAR(255) DEFAULT ' ' NOT NULL
);

IF NOT EXISTS (SELECT 1 FROM KSQL_USERTABLES WHERE KSQL_TABNAME = 'T_CEA_ASSERSEEKCONFENTRY')
CREATE TABLE T_CEA_ASSERSEEKCONFENTRY (
	FID BIGINT DEFAULT 0 NOT NULL,
	FENTRYID BIGINT DEFAULT 0 NOT NULL,
	FSEQ INT DEFAULT 0 NOT NULL,
	FPERFORGID BIGINT DEFAULT 0 NOT NULL
);


