IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_TABNAME = 'T_CEA_ASSESSACTIVITY' AND KSQL_COL_NAME ='FOVERTIME') 
 ALTER TABLE T_CEA_ASSESSACTIVITY ADD (FOVERTIME DATETIME);

IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_TABNAME = 'T_CEA_ASSESSOBJ' AND KSQL_COL_NAME ='FREPORTWORKID') 
 ALTER TABLE T_CEA_ASSESSOBJ ADD (FREPORTWORKID BIGINT DEFAULT 0 NOT NULL);
 
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_TABNAME = 'T_CEA_ASSESSOBJ' AND KSQL_COL_NAME ='FHASREPORTWORK') 
 ALTER TABLE T_CEA_ASSESSOBJ ADD (FHASREPORTWORK VARCHAR(44) DEFAULT ' ' NOT NULL); 
 
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_TABNAME = 'T_CEA_ASSESSOBJ' AND KSQL_COL_NAME ='FSHOWSCORE') 
 ALTER TABLE T_CEA_ASSESSOBJ ADD (FSHOWSCORE VARCHAR(44) DEFAULT ' ' NOT NULL); 
 
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_TABNAME = 'T_CEA_ASSESSFORMROWFIX' AND KSQL_COL_NAME ='FLEVELMAP') 
 ALTER TABLE T_CEA_ASSESSFORMROWFIX ADD (FLEVELMAP VARCHAR(50) DEFAULT ' ' NOT NULL);
 
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_TABNAME = 'T_CEA_ASSESSFORMROWFIX' AND KSQL_COL_NAME ='FINDICATORTYPE') 
 ALTER TABLE T_CEA_ASSESSFORMROWFIX ADD (FINDICATORTYPE VARCHAR(2) DEFAULT ' ' NOT NULL); 
 
IF NOT EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_TABNAME = 'T_CEA_ASSOBJSCOITEMINS' AND KSQL_COL_NAME ='FMAPSCORE') 
 ALTER TABLE T_CEA_ASSOBJSCOITEMINS ADD (FMAPSCORE VARCHAR(50) DEFAULT ' ' NOT NULL);
 
 
 -- 去掉测评表指标维度默认0
--IF EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_TABNAME = 'T_CEA_ASSESSFORMROWFIX' AND KSQL_COL_NAME ='FINDICATORWEIGHT') 
-- ALTER TABLE T_CEA_ASSESSFORMROWFIX ALTER (FINDICATORWEIGHT DECIMAL(23, 2));
-- 调整测评对象得分字段精度 
--IF EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_TABNAME = 'T_CEA_ASSESSOBJ' AND KSQL_COL_NAME ='FCALSCORE') 
-- ALTER TABLE T_CEA_ASSESSOBJ ALTER (FCALSCORE DECIMAL(23, 6) DEFAULT 0 NOT NULL);
 
--IF EXISTS (SELECT 1 FROM KSQL_USERCOLUMNS WHERE KSQL_COL_TABNAME = 'T_CEA_ASSESSOBJ' AND KSQL_COL_NAME ='FMODSCORE') 
-- ALTER TABLE T_CEA_ASSESSOBJ ALTER (FMODSCORE DECIMAL(23, 6) DEFAULT 0 NOT NULL);   
 
 
