<?xml version="1.0" encoding="UTF-8"?>

<DeployAppMetadata>
  <Multilanguage>false</Multilanguage>
  <MasterId>4513U+LB/HOD</MasterId>
  <Id>4513U+LB/HOD</Id>
  <DesignMetas>
    <DesignAppMeta>
      <DevType>0</DevType>
      <AppVersion>1.5.0</AppVersion>
      <Modifier>1425399182121766912</Modifier>
      <DataXml>
        <AppMetadata>
          <DevType>0</DevType>
          <AppFunctionPackets>
            <AppFunctionPacketElement>
              <Number>MainPage</Number>
              <Name>首页</Name>
              <Description/>
              <Id>4513U+N6ITIN</Id>
              <Leaf>0</Leaf>
              <ParentId/>
              <Seq>1</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>cea_activitysetting</Number>
              <Name>测评活动设置</Name>
              <Description>测评活动设置</Description>
              <Id>45H2DV8V8L98</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>2</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>cea_assessactmanager</Number>
              <Name>测评活动管理</Name>
              <Description/>
              <Id>45KU3EVJIJRN</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>3</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>cea_assessobj</Number>
              <Name>测评对象</Name>
              <Description/>
              <Id>45KUGRD4HA1J</Id>
              <Leaf>false</Leaf>
              <ParentId>45KU3EVJIJRN</ParentId>
              <Seq>1</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>cea_assesstask</Number>
              <Name>测评任务</Name>
              <Description/>
              <Id>45O23XJ9UE1I</Id>
              <Leaf>false</Leaf>
              <ParentId>45KU3EVJIJRN</ParentId>
              <Seq>2</Seq>
            </AppFunctionPacketElement>
          </AppFunctionPackets>
          <AppMenus>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>3b67d0d1e1</Number>
              <FormName>测评活动列表</FormName>
              <FormNumber>cea_assactivity_list</FormNumber>
              <Parameter>{"pageMode":"2","isShowTitle":"true"}</Parameter>
              <Id>1974815632666936320</Id>
              <Seq>1</Seq>
              <FormId>46K5582K9OJZ</FormId>
              <ParameterType>ListShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj4_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>4513U+LB/HOD</ParentId>
              <VectorImage>kdfont kdfont-cebianlantubiao1beifen</VectorImage>
              <Name>测评活动</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Caption>帮助中心</Caption>
              <Description>帮助中心</Description>
              <FormName>应用入门中心</FormName>
              <FormNumber>bas_appstarted</FormNumber>
              <Parameter>{"caption":{"zh_CN":"帮助中心"}}</Parameter>
              <Id>4513UXP+3K6#hpce</Id>
              <Seq>32766</Seq>
              <FormId>/WXHVRP15OWF</FormId>
              <IconShortcut>/icons/pc/entrance/helpcentre.png</IconShortcut>
              <Visible>0</Visible>
              <ParentId>4513U+LB/HOD</ParentId>
              <VectorImage>kdfont kdfont-tishixinxi_l</VectorImage>
              <Name>帮助中心</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
          </AppMenus>
          <Isv>tdkw</Isv>
          <Number>cds0_cea</Number>
          <Id>4513U+LB/HOD</Id>
          <BizCloudID>24BBHV84L8E9</BizCloudID>
          <ParentId/>
          <MasterId/>
          <AppElement>
            <AppElement>
              <MainFormNumber>cds0_cea_apphome</MainFormNumber>
              <Description>能力素质考核</Description>
              <DbRoute>opmc</DbRoute>
              <OpenType>0</OpenType>
              <AllUserApp>0</AllUserApp>
              <Number>cds0_cea</Number>
              <Id>4513U+LB/HOD</Id>
              <Seq>5</Seq>
              <MainFormType>0</MainFormType>
              <DependencyID/>
              <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
              <OrgFunc/>
              <Visible>1</Visible>
              <Dependency/>
              <HelpURL/>
              <Label/>
              <MainFormName>360测评_应用首页</MainFormName>
              <Version>1.5.0</Version>
              <BackImage/>
              <HomeURL/>
              <MainFormID>4513U0O7NQYT</MainFormID>
              <Name>能力素质考核</Name>
              <SimpleNumber/>
              <UserType>,1,</UserType>
              <DeployStatus>2</DeployStatus>
            </AppElement>
          </AppElement>
          <InheritPath/>
        </AppMetadata>
      </DataXml>
      <Description></Description>
      <DbRoute>opmc</DbRoute>
      <Isv>tdkw</Isv>
      <OpenType>0</OpenType>
      <AllUserApp>0</AllUserApp>
      <Number>cds0_cea</Number>
      <IndustryId>0</IndustryId>
      <Id>4513U+LB/HOD</Id>
      <Seq>5</Seq>
      <CreateDate>1717147675563</CreateDate>
      <MainFormType>0</MainFormType>
      <BizCloudID>24BBHV84L8E9</BizCloudID>
      <DependencyID></DependencyID>
      <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
      <OrgFunc></OrgFunc>
      <Visible>1</Visible>
      <ModifyDate>1758855549697</ModifyDate>
      <Dependency></Dependency>
      <HelpURL></HelpURL>
      <Label></Label>
      <ModelType>AppModel</ModelType>
      <MainFormName>360测评_应用首页</MainFormName>
      <ParentId></ParentId>
      <BackImage></BackImage>
      <HomeURL></HomeURL>
      <MasterId></MasterId>
      <Creater>1957383068159312896</Creater>
      <MainFormID>4513U0O7NQYT</MainFormID>
      <SimpleNumber></SimpleNumber>
      <InheritPath></InheritPath>
      <RefAppId></RefAppId>
      <UserType>,1,</UserType>
      <DeployStatus>2</DeployStatus>
    </DesignAppMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployAppMetadata>
