/**
 * This is a kingdee cosmic template project that is automatically generated by the Kingdee cosmic development assistant plugin. 
 * If there are any issues during the use process, you can provide feedback to the kingdee developer community website.
 * Website: https://developer.kingdee.com/developer?productLineId=29
 * Author: liebin.zheng
 * Generate Date: 2024-11-20 19:59:19
 */
package tdkw.cosmic.debug;

/**
 * 启动本地应用程序(微服务节点)
 */
public class DebugApplication {
	
	

    public static void main(String[] args) {
    	
//    	Thread.currentThread().setContextClassLoader(new KDSecurityClassLoader(Thread.currentThread().getContextClassLoader()));
    	
//        Launcher cosmic = new Launcher(false);
//
//        cosmic.setClusterNumber("cosmic");
//        cosmic.setTenantNumber("ierp");
//
////        cosmic.setConfigUrl("127.0.0.1:2181?user=zk&password=******");
//        cosmic.setConfigUrl("127.0.0.1:2181");
//
////        cosmic.setMcServerUrl("http://127.0.0.1:8090");
//        cosmic.setMcServerUrl("http://127.0.0.1:8090/");
//
//        cosmic.setWebResPath("D:/kingdee/demo/mservice/static-file-service");
//
////        cosmic.setFsServerUrl("127.0.0.1", 8100);
////        cosmic.setImageServerUrl("127.0.0.1", 8100);
//
//        //自定义本地苍穹调试服务的端口
//        cosmic.setCosmicWepPort(8881);
//
//        cosmic.start();

        Launcher cosmic = new Launcher();
        cosmic.setClusterNumber("cosmic");
        cosmic.setTenantNumber("ierp");
        cosmic.setServerIp("172.20.106.77");
        // 本地缓存指向
        cosmic.set("redis.serversForCache","172.20.106.77:6379");
        cosmic.set("redis.serversForSession","172.20.106.77:6379");
        cosmic.set("algo.storage.redis.url","172.20.106.77:6379");


        cosmic.setAppName("cosmic-sxf-WfNHk1k6");
                cosmic.setWebResPath("D:\\kingdee\\webapp");
//        cosmic.setWebAppPath("D:\\kingdee\\webapp");
        cosmic.setConfigUrl("172.20.106.77:2181/?user=zookeeper&password=hrit2024");
        // 调度中心
        cosmic.set("Schedule.zk.server", "172.20.106.77:2181/?user=zookeeper&password=hrit2024");

//        cosmic.setMcServerUrl("http://172.20.106.77:8090");
        cosmic.set("mqConfigFiles.config", "consumermqconfig.xml");
        // 调试mq消费的代码块,该参数为false，本节点将不会消费mq消息  会影响本地工作流
        cosmic.set("mq.consumer.register", "true");
        cosmic.set("mq.debug.queue.tag", "sxf_123_queue");
        cosmic.set("lightweightdeploy", "true");  //标注环境为轻量级
        cosmic.set("redismodelcache.enablelua", "false");  //轻量级不能用lua，设为false
        cosmic.set("dubbo.service.lookup.local", "true");

        cosmic.set("tempfile.cachetype" , "disk");
        cosmic.set("diskcache.path" , "D:/tempfile");

        cosmic.setStartWithQing(false);
        cosmic.start();
        
    }
}