<?xml version="1.0" encoding="UTF-8"?>

<DeployAppMetadata>
  <Multilanguage>false</Multilanguage>
  <MasterId>1WXBPN7+OHJZ</MasterId>
  <Id>4C44KE2RK8W9</Id>
  <DesignMetas>
    <DesignAppMeta>
      <DevType>2</DevType>
      <AppVersion>1.5.0</AppVersion>
      <Modifier>2027699484829418496</Modifier>
      <DataXml>
        <AppMetadata>
          <DevType>2</DevType>
          <Isv>tdkw</Isv>
          <Number>tdkw_hspm_ext</Number>
          <Id>4C44KE2RK8W9</Id>
          <ParentId>1WXBPN7+OHJZ</ParentId>
          <MasterId>1WXBPN7+OHJZ</MasterId>
          <AppElement>
            <AppElement>
              <Number>tdkw_hspm_ext</Number>
              <Id>4C44KE2RK8W9</Id>
              <UserType>,1,</UserType>
            </AppElement>
          </AppElement>
          <InheritPath>1WXBPN7+OHJZ</InheritPath>
        </AppMetadata>
      </DataXml>
      <Description></Description>
      <DbRoute>hr</DbRoute>
      <Isv>tdkw</Isv>
      <OpenType>0</OpenType>
      <AllUserApp>0</AllUserApp>
      <Number>tdkw_hspm_ext</Number>
      <IndustryId>0</IndustryId>
      <Id>4C44KE2RK8W9</Id>
      <Seq>10</Seq>
      <CreateDate>1724986100199</CreateDate>
      <MainFormType>0</MainFormType>
      <BizCloudID>11FWSEDXBS99</BizCloudID>
      <DependencyID></DependencyID>
      <Image>/icons/pc/entrance/hr_rlcbywlx_48_48.png</Image>
      <OrgFunc></OrgFunc>
      <Visible>1</Visible>
      <Dependency></Dependency>
      <HelpURL></HelpURL>
      <Label></Label>
      <ModelType>AppModel</ModelType>
      <MainFormName>人员信息_应用首页</MainFormName>
      <ParentId>1WXBPN7+OHJZ</ParentId>
      <BackImage></BackImage>
      <HomeURL></HomeURL>
      <MasterId>1WXBPN7+OHJZ</MasterId>
      <Creater>2027699484829418496</Creater>
      <MainFormID>1WXBPNUTU+VH</MainFormID>
      <SimpleNumber></SimpleNumber>
      <InheritPath>1WXBPN7+OHJZ</InheritPath>
      <RefAppId></RefAppId>
      <UserType>,1,</UserType>
      <DeployStatus>2</DeployStatus>
    </DesignAppMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployAppMetadata>
