<?xml version="1.0" encoding="UTF-8"?>

<DeployAppMetadata>
  <Multilanguage>false</Multilanguage>
  <MasterId>3FFIHFYFQM9X</MasterId>
  <Id>3FFIHFYFQM9X</Id>
  <DesignMetas>
    <DesignAppMeta>
      <DevType>0</DevType>
      <AppVersion>1.5.0</AppVersion>
      <Modifier>1425399182121766912</Modifier>
      <DataXml>
        <AppMetadata>
          <DevType>0</DevType>
          <AppFunctionPackets>
            <AppFunctionPacketElement>
              <Number>MainPage</Number>
              <Name>首页</Name>
              <Description/>
              <Id>3FFIHGAI4WH+</Id>
              <Leaf>0</Leaf>
              <ParentId/>
              <Seq>1</Seq>
            </AppFunctionPacketElement>
          </AppFunctionPackets>
          <AppMenus>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>2b6fb6979f</Number>
              <FormName>我的团队</FormName>
              <FormNumber>tdkw_myteam_epsilon</FormNumber>
              <Parameter/>
              <Id>1737830314614518784</Id>
              <Seq>1</Seq>
              <FormId>3FFJ+4Q867TO</FormId>
              <ParameterType>FormShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj2_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>3FFIHFYFQM9X</ParentId>
              <VectorImage>kdfont kdfont-tongyongtubiao4</VectorImage>
              <Name>我的团队</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>72ccbff32a</Number>
              <FormName>招聘需求申请单</FormName>
              <FormNumber>tdkw_rec_apply_bill</FormNumber>
              <Parameter/>
              <Id>1744251834882623488</Id>
              <Seq>2</Seq>
              <FormId>3=TQ5QXQONIW</FormId>
              <ParameterType>BillShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj5_48_48.png</IconShortcut>
              <Visible>false</Visible>
              <ParentId>3FFIHFYFQM9X</ParentId>
              <VectorImage>kdfont kdfont-cebianlantubiao6beifen</VectorImage>
              <Name>招聘需求</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>d790173a4e</Number>
              <FormName>团队绩效</FormName>
              <FormNumber>tdkw_teamperform</FormNumber>
              <Parameter/>
              <Id>1744320532825791488</Id>
              <Seq>3</Seq>
              <FormId>3G8SWII3M1V1</FormId>
              <ParameterType>FormShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj5_48_48.png</IconShortcut>
              <Visible>false</Visible>
              <ParentId>3FFIHFYFQM9X</ParentId>
              <VectorImage>kdfont kdfont-cebianlantubiao6beifen</VectorImage>
              <Name>团队绩效</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Description/>
              <OpenType>MainNewTabPage</OpenType>
              <Number>e05b1ad989</Number>
              <FormName>职能团队</FormName>
              <FormNumber>tdkw_myteam_positionson</FormNumber>
              <Parameter/>
              <Id>1805216373035752448</Id>
              <Seq>4</Seq>
              <FormId>3N27CL5U=H69</FormId>
              <ParameterType>ReportShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj2_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <ParentId>3FFIHFYFQM9X</ParentId>
              <VectorImage>kdfont kdfont-tongyongtubiao4</VectorImage>
              <Name>职能团队</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
            <AppMenuElement>
              <Caption>帮助中心</Caption>
              <Description>帮助中心</Description>
              <FormName>应用入门中心</FormName>
              <FormNumber>bas_appstarted</FormNumber>
              <Parameter>{"caption":{"zh_CN":"帮助中心"}}</Parameter>
              <Id>3FFJ6SDUM29#hpce</Id>
              <Seq>32766</Seq>
              <FormId>/WXHVRP15OWF</FormId>
              <IconShortcut>/icons/pc/entrance/helpcentre.png</IconShortcut>
              <Visible>0</Visible>
              <ParentId>3FFIHFYFQM9X</ParentId>
              <VectorImage>kdfont kdfont-tishixinxi_l</VectorImage>
              <Name>帮助中心</Name>
              <MenuType>page</MenuType>
            </AppMenuElement>
          </AppMenus>
          <Isv>tdkw</Isv>
          <Number>tdkw_myteam</Number>
          <Id>3FFIHFYFQM9X</Id>
          <BizCloudID>18Y2T5WS5AFV</BizCloudID>
          <ParentId/>
          <MasterId/>
          <AppElement>
            <AppElement>
              <MainFormNumber>tdkw_myteam_apphome</MainFormNumber>
              <Description/>
              <DbRoute>secd</DbRoute>
              <OpenType>0</OpenType>
              <AllUserApp>0</AllUserApp>
              <Number>tdkw_myteam</Number>
              <Id>3FFIHFYFQM9X</Id>
              <Seq>268</Seq>
              <MainFormType>0</MainFormType>
              <DependencyID/>
              <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
              <OrgFunc/>
              <Visible>1</Visible>
              <Dependency/>
              <HelpURL/>
              <Label/>
              <MainFormName>我的团队_应用首页</MainFormName>
              <Version>1.5.0</Version>
              <BackImage/>
              <HomeURL/>
              <MainFormID>3FFIHN2GFLPM</MainFormID>
              <Name>经理人自助</Name>
              <SimpleNumber/>
              <UserType>,1,</UserType>
              <DeployStatus>2</DeployStatus>
            </AppElement>
          </AppElement>
          <InheritPath/>
        </AppMetadata>
      </DataXml>
      <Description></Description>
      <DbRoute>secd</DbRoute>
      <Isv>tdkw</Isv>
      <OpenType>0</OpenType>
      <AllUserApp>0</AllUserApp>
      <Number>tdkw_myteam</Number>
      <IndustryId>0</IndustryId>
      <Id>3FFIHFYFQM9X</Id>
      <Seq>268</Seq>
      <CreateDate>1690359377555</CreateDate>
      <MainFormType>0</MainFormType>
      <BizCloudID>18Y2T5WS5AFV</BizCloudID>
      <DependencyID></DependencyID>
      <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
      <OrgFunc></OrgFunc>
      <Visible>1</Visible>
      <ModifyDate>1734438697029</ModifyDate>
      <Dependency></Dependency>
      <HelpURL></HelpURL>
      <Label></Label>
      <ModelType>AppModel</ModelType>
      <MainFormName>我的团队_应用首页</MainFormName>
      <ParentId></ParentId>
      <BackImage></BackImage>
      <HomeURL></HomeURL>
      <MasterId></MasterId>
      <Creater>1681098732466095104</Creater>
      <MainFormID>3FFIHN2GFLPM</MainFormID>
      <SimpleNumber></SimpleNumber>
      <InheritPath></InheritPath>
      <RefAppId></RefAppId>
      <UserType>,1,</UserType>
      <DeployStatus>2</DeployStatus>
    </DesignAppMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployAppMetadata>
