<?xml version="1.0" encoding="UTF-8"?>

<DeployAppMetadata>
  <Multilanguage>false</Multilanguage>
  <MasterId>217YZTTABIJI</MasterId>
  <Id>4HRG9IKTXLSA</Id>
  <DesignMetas>
    <DesignAppMeta>
      <DevType>2</DevType>
      <AppVersion>1.5.0</AppVersion>
      <Modifier>2027699484829418496</Modifier>
      <DataXml>
        <AppMetadata>
          <DevType>2</DevType>
          <AppFunctionPackets>
            <AppFunctionPacketElement>
              <Number>indicia</Number>
              <Name>职衔</Name>
              <Description/>
              <Id>4I=OU/3XN1XB</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>5</Seq>
            </AppFunctionPacketElement>
          </AppFunctionPackets>
          <Isv>tdkw</Isv>
          <Number>tdkw_hjm_ext</Number>
          <Id>4HRG9IKTXLSA</Id>
          <ParentId>217YZTTABIJI</ParentId>
          <MasterId>217YZTTABIJI</MasterId>
          <AppElement>
            <AppElement>
              <Number>tdkw_hjm_ext</Number>
              <Id>4HRG9IKTXLSA</Id>
              <UserType>,1,</UserType>
            </AppElement>
          </AppElement>
          <InheritPath>217YZTTABIJI</InheritPath>
        </AppMetadata>
      </DataXml>
      <Description></Description>
      <DbRoute>hr</DbRoute>
      <Isv>tdkw</Isv>
      <OpenType>0</OpenType>
      <AllUserApp>0</AllUserApp>
      <Number>tdkw_hjm_ext</Number>
      <IndustryId>0</IndustryId>
      <Id>4HRG9IKTXLSA</Id>
      <Seq>122</Seq>
      <CreateDate>1730443436704</CreateDate>
      <MainFormType>0</MainFormType>
      <BizCloudID>0MUWQ6HSY5JA</BizCloudID>
      <DependencyID></DependencyID>
      <Image>/icons/pc/entrance/hr_zwgl_48_48.png</Image>
      <OrgFunc></OrgFunc>
      <Visible>1</Visible>
      <ModifyDate>1730971421635</ModifyDate>
      <Dependency></Dependency>
      <HelpURL></HelpURL>
      <Label></Label>
      <ModelType>AppModel</ModelType>
      <MainFormName>职位管理_应用首页</MainFormName>
      <ParentId>217YZTTABIJI</ParentId>
      <BackImage></BackImage>
      <HomeURL></HomeURL>
      <MasterId>217YZTTABIJI</MasterId>
      <Creater>2027699484829418496</Creater>
      <MainFormID>217YZUE3LUJ1</MainFormID>
      <SimpleNumber></SimpleNumber>
      <InheritPath>217YZTTABIJI</InheritPath>
      <RefAppId></RefAppId>
      <UserType>,1,</UserType>
      <DeployStatus>2</DeployStatus>
    </DesignAppMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployAppMetadata>
