IF NOT EXISTS(SELECT 1 FROM T_PERM_CUSTPERMSERV WHERE FAPPID = '4513U+LB/HOD')

INSERT INTO T_PERM_CUSTPERMSERV(FID,FSERVFACTORY,FSERVNAME,FISSKIP,FISAND,FAPPID,FSERVAPPNUM) VALUES(972934157644546086,'kd.hrmp.hrcs.servicehelper.ServiceFactory','IHRCSDataPermissionService','0','1','4513U+LB/HOD','hrcs');

